import { useState } from 'react';
import FinalQuiz from '../../shared/FinalQuiz';
import { LatinRuns } from '../../shared/bidi';
import { Signature } from '../../shared/Signature';
import { SOURCE_SECTIONS, TRAINING1, TRAINING2, TRAINING3, TRAINING4, TRAINING5, DETECTIVE, IQ200, MEANING, MINI_TEST, LESSON_TITLE_24 } from './data';

type Props={onExit:()=>void};
const answers=[['many','a little','many','a few','a little','a few','a little','many'],['some','any','any','some','any','any','some','any'],['many','much','many','much','much','many','much','many'],['a few','a little','a few','a little','a few','a little','a few','a little'],['a few','few','a few','few','a few','few']];
const options=(kind:number)=>kind===0?['many','much','a few','a little']:kind===1?['some','any']:kind===2?['many','much']:kind===3?['a few','a little']:['few','a few'];
function Practice({title,items,kind,correct}:{title:string;items:string[];kind:number;correct:string[]}){
 const [pick,setPick]=useState<Record<number,string>>({}); const [checked,setChecked]=useState(false); const done=items.length===Object.keys(pick).length;
 return <section className="mt-5 rounded-3xl border-2 border-cyan-200 bg-cyan-50/60 p-4" data-exercise={title}>
  <h3 className="text-xl font-black text-cyan-950">{title}</h3><div className="mt-3 grid gap-3 md:grid-cols-2">
   {items.map((q,i)=><div key={q} className={`rounded-2xl border-2 p-3 ${checked?(pick[i]===correct[i]?'border-emerald-300 bg-emerald-50':'border-rose-300 bg-rose-50'):'border-white bg-white'}`}>
    <div dir="rtl" className="font-bold"><span className="text-cyan-700">{i+1}. </span><LatinRuns text={q}/></div>
    <div dir="ltr" className="mt-2 flex flex-wrap gap-2">{options(kind).map(o=><button key={o} type="button" aria-pressed={pick[i]===o} disabled={checked} onClick={()=>setPick({...pick,[i]:o})} className={`rounded-xl border-2 px-3 py-1 font-en font-bold ${pick[i]===o?'border-slate-900 bg-slate-900 text-white':'border-slate-200 bg-white'} disabled:opacity-80`}>{o}</button>)}</div>
    {checked&&<div className="mt-2 text-sm font-bold">{pick[i]===correct[i]?'✓ صحيح!':'✕'} {pick[i]===correct[i]?'':'الإجابة: '+correct[i]}</div>}
   </div>)}
  </div><button type="button" disabled={!done||checked} onClick={()=>setChecked(true)} className="mt-4 rounded-xl bg-cyan-800 px-4 py-2 font-bold text-white disabled:opacity-30">تحقق من الإجابات</button>
  {checked&&<button type="button" onClick={()=>{setPick({});setChecked(false)}} className="mr-2 rounded-xl bg-slate-200 px-4 py-2 font-bold">↺ إعادة</button>}
 </section>
}
function TextBlock({text}:{text:string}){return <div className="space-y-2 text-base font-semibold leading-8 text-slate-700">{text.split('\n').map((line,i)=><div key={i} dir="rtl"><LatinRuns text={line}/></div>)}</div>}
export function SlideView24({s}:{s:(typeof SOURCE_SECTIONS)[number]}){return <article dir="rtl" data-source-section={s.title} className="scroll-mt-4 rounded-3xl border-2 border-slate-100 bg-white p-5 shadow-sm"><div className="mb-3 flex items-center gap-2"><span className="rounded-full bg-cyan-100 px-3 py-1 text-xs font-black text-cyan-900">SOURCE {s.id}</span><h2 className="text-2xl font-black text-slate-900">{s.title}</h2></div><TextBlock text={s.body}/></article>}
export default function Lesson24({onExit}:Props){return <main dir="rtl" className="min-h-screen bg-gradient-to-b from-cyan-50 via-white to-indigo-50 px-3 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-5xl"><button onClick={onExit} className="mb-4 rounded-xl bg-white px-4 py-2 font-bold shadow">← العودة للدروس</button><header className="rounded-[2rem] bg-gradient-to-br from-cyan-700 to-indigo-800 p-6 text-white shadow-xl"><div className="text-sm font-black tracking-widest text-cyan-100">ENGLISHWITHSOMER · QUANTITY LAB</div><h1 className="mt-2 text-3xl font-black sm:text-5xl">{LESSON_TITLE_24}</h1><div dir="ltr" className="mt-3 font-en text-xl font-black">some / any / much / many / a lot of / a few / few / a little / little</div><p className="mt-4 text-lg font-bold">من التصنيف في الدرس 23 إلى التعبير الدقيق عن الكمية: صنّف الاسم، افهم المعنى، ثم اختر الأداة.</p></header><div className="my-5 rounded-3xl border-2 border-amber-200 bg-amber-50 p-5"><h2 className="text-2xl font-black">🧭 QUANTIFIER COMMAND CENTER</h2><p className="mt-2 font-bold">1. ما نوع الاسم؟ Countable plural أم Uncountable؟<br/>2. ما المعنى؟ some أم many أم much أم a lot of أم a few أم few أم a little أم little أم any؟<br/>3. ما نوع الجملة؟ Positive أم Question أم Negative؟<br/>4. هل الكمية neutral أم positive/sufficient أم shortage؟</p></div><div className="grid gap-4">{SOURCE_SECTIONS.map(s=><SlideView24 key={s.id} s={s}/>)}</div>
 <Practice title="🔥 تدريب ① — اختر أداة الكمية" items={TRAINING1} kind={0} correct={answers[0]}/><Practice title="🔥 تدريب ② — SOME أم ANY؟" items={TRAINING2} kind={1} correct={answers[1]}/><Practice title="🔥 تدريب ③ — MANY أم MUCH؟" items={TRAINING3} kind={2} correct={answers[2]}/><Practice title="🔥 تدريب ④ — A FEW أم A LITTLE؟" items={TRAINING4} kind={3} correct={answers[3]}/><Practice title="🚨 تدريب ⑤ — FEW أم A FEW؟" items={TRAINING5} kind={4} correct={answers[4]}/>
 <InteractiveText title="🕵️ Grammar Detective — صحح كل الجمل" items={DETECTIVE}/><InteractiveText title="🚀 IQ200 Challenge — صحح واشرح" items={IQ200}/><InteractiveText title="🧠 Meaning Challenge" items={MEANING}/>
 <section className="mt-5 rounded-3xl border-2 border-amber-300 bg-gradient-to-br from-amber-50 to-white p-5"><h2 className="text-2xl font-black">🏆 FINAL BOSS — مطعم Quantity Lab</h2><TextBlock text={'12 customers · 3 tables · some rice · some water · 2 chefs · little time · a lot of food · a few empty chairs\nاكتب قصة قصيرة من 10 جمل عن المطعم، واستخدم some، any، many، much، a lot of، a few، little أو a little، There is، There are، How many أو How much.'}/></section>
 <section className="mt-5 rounded-3xl border-2 border-indigo-200 bg-white p-5"><h2 className="text-2xl font-black">🧠 الاختبار النهائي المصغر — 8 أسئلة</h2>{MINI_TEST.map(([q,opts],i)=><div key={q} className="mt-3 rounded-2xl bg-indigo-50 p-3"><b>{i+1}. </b><LatinRuns text={q}/><div dir="ltr" className="mt-2 flex flex-wrap gap-2">{opts.map(o=><span key={o} className="rounded-lg bg-white px-3 py-1 font-en font-bold">{o}</span>)}</div></div>)}</section>
 <section className="mt-5 rounded-3xl border-2 border-slate-200 bg-white p-5"><h2 className="text-2xl font-black">📝 Final Quiz — Quantifiers</h2><FinalQuiz lesson={24} accent="bg-cyan-700"/></section><Signature/></div></main>}
function InteractiveText({title,items}:{title:string;items:string[]}){const [checked,setChecked]=useState(false);return <section className="mt-5 rounded-3xl border-2 border-violet-200 bg-violet-50 p-5"><h2 className="text-2xl font-black">{title}</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{items.map((x,i)=><div key={x} className="rounded-xl bg-white p-3 font-bold"><b>{i+1}. </b><LatinRuns text={x}/></div>)}</div><button onClick={()=>setChecked(!checked)} className="mt-4 rounded-xl bg-violet-800 px-4 py-2 font-bold text-white">{checked?'إخفاء التعليمات':'تحقق من الإجابات'}</button>{checked&&<p className="mt-3 font-bold">راجع النوع والمعنى: many/a few/few للمعدود الجمع، much/a little/little لغير المعدود، some/any/a lot of/lots of للنوعين. الجملة 10 في Grammar Detective صحيحة.</p>}</section>}
