// ============================================================
// الدرس 30 — مراجعة شاملة لنظام الماضي
// 🎛️ THE PAST CONTROL ROOM — غرفة التحكم بنظام الماضي الكامل
// Past Simple + Past Continuous + Past Perfect + Past Perfect Continuous
//
// المصدر المورّد هو المرجع الحرفي: لا اختصار ولا إعادة صياغة ولا حذف.
// كل سطر من المصدر مسجَّل في SOURCE_SECTIONS ويُعرض فعليًا في Lesson30.tsx،
// والفحص الآلي (scripts/audit-lesson30.mjs) يتحقق من التغطية.
// ============================================================

export const LESSON_TITLE_30 = "الدرس 30: مراجعة شاملة لنظام الماضي";
export const LESSON_SUBTITLE_30 = "🧠 IQ200 — Past Simple + Past Continuous + Past Perfect + Past Perfect Continuous";
export const LAB_NAME_30 = "THE PAST CONTROL ROOM";
export const LAB_MOTTO_30 = "📸 What happened? · 🎥 What was happening? · ⏪ What had happened? · ⏪🎥 What had been happening?";

export type Tone30 = "neutral" | "en" | "good" | "bad" | "warn" | "head" | "subhead";

// ============================================================
// سجل المصدر (Source Ledger) — كل قسم = عنوانه من المصدر + وحداته الحرفية.
// ============================================================
export type SourceSection30 = {
  id: string;
  num?: number;
  title: string;
  /** وحدات حرفية من المصدر — كل سطر كما هو (بدون **). */
  units: string[];
};

export const SOURCE_SECTIONS: SourceSection30[] = [
  {
    id: "cover",
    title: "الغلاف — الدرس 30: مراجعة شاملة لنظام الماضي",
    units: [
      "الدرس 30: مراجعة شاملة لنظام الماضي",
      "🧠 IQ200 — Past Simple + Past Continuous + Past Perfect + Past Perfect Continuous",
    ],
  },
  {
    id: "opening",
    title: "الافتتاح — وصلنا الآن إلى نقطة مهمة جدًا",
    units: [
      "وصلنا الآن إلى نقطة مهمة جدًا.",
      "حتى الدرس 29 أصبح لدينا نظام كامل من أزمنة الماضي:",
      "① Past Simple",
      "→ ماذا حدث؟",
      "② Past Continuous",
      "→ ماذا كان يحدث؟",
      "③ Past Perfect",
      "→ ماذا كان قد حدث قبل حدث ماضٍ آخر؟",
      "④ Past Perfect Continuous",
      "→ ماذا كان مستمرًا لفترة قبل حدث ماضٍ آخر؟",
      "لذلك لن نضيف زمنًا جديدًا الآن.",
      "سنقوم ببناء \"نظام تحكم\" كامل، بحيث تستطيع اختيار الزمن الصحيح من المعنى، وليس من الكلمات المحفوظة فقط.",
    ],
  },
  {
    id: "objectives",
    title: "🎯 أهداف الدرس",
    units: [
      "بنهاية هذا الدرس يجب أن تستطيع:",
      "① التمييز بين الأزمنة الأربعة بسرعة.",
      "② قراءة قصة وتحديد الزمن المناسب لكل فعل.",
      "③ ترتيب عدة أحداث على خط زمني.",
      "④ استخدام when و while و before و after و by the time بشكل صحيح.",
      "⑤ معرفة متى يكون Past Perfect ضروريًا ومتى لا نحتاجه.",
      "⑥ معرفة الفرق بين النتيجة والنشاط والمدة.",
      "⑦ اكتشاف الأخطاء المتقدمة.",
      "⑧ دمج الأزمنة الأربعة في قصة واحدة.",
      "⑨ التعامل مع أسئلة IQ200 التي لا تعطيك الإجابة بشكل مباشر.",
      "⑩ الاستعداد للانتقال إلى مرحلة الأزمنة المستقبلية لاحقًا بعد تثبيت نظام الماضي.",
    ],
  },
  {
    id: "s1",
    num: 1,
    title: "① 🧠 النظام الكامل",
    units: [
      "لنبدأ من الصورة الكبرى.",
      "Past Simple",
      "I opened the door.",
      "فتحت الباب.",
      "السؤال:",
      "ماذا حدث؟",
      "Past Continuous",
      "I was opening the door.",
      "كنت أفتح الباب.",
      "السؤال:",
      "ماذا كان يحدث في تلك اللحظة؟",
      "Past Perfect",
      "I had opened the door before the lights went out.",
      "كنت قد فتحت الباب قبل أن تنطفئ الأضواء.",
      "السؤال:",
      "ماذا كان قد حدث قبل حدث ماضٍ آخر؟",
      "Past Perfect Continuous",
      "I had been opening boxes for an hour before the lights went out.",
      "كنت أفتح الصناديق لمدة ساعة قبل أن تنطفئ الأضواء.",
      "السؤال:",
      "ما النشاط الذي كان مستمرًا لفترة قبل حدث ماضٍ آخر؟",
    ],
  },
  {
    id: "s2",
    num: 2,
    title: "② 🧠 لا تحفظ الزمن... اسأل أربعة أسئلة",
    units: [
      "عندما ترى جملة جديدة، اسأل:",
      "السؤال 1",
      "هل هذا مجرد حدث ماضٍ؟",
      "→ Past Simple",
      "السؤال 2",
      "هل كان الفعل مستمرًا في لحظة ماضية؟",
      "→ Past Continuous",
      "السؤال 3",
      "هل حدث الفعل قبل حدث ماضٍ آخر؟",
      "→ Past Perfect",
      "السؤال 4",
      "هل كان الفعل مستمرًا لفترة قبل حدث ماضٍ آخر؟",
      "→ Past Perfect Continuous",
      "هذه هي \"آلة اختيار الزمن\".",
    ],
  },
  {
    id: "s3",
    num: 3,
    title: "③ 📸 Past Simple",
    units: [
      "Past Simple يروي الأحداث.",
      "مثال:",
      "Leo opened the window.",
      "He looked outside.",
      "He saw a bird.",
      "He smiled.",
      "هذه سلسلة أحداث:",
      "① opened",
      "② looked",
      "③ saw",
      "④ smiled",
      "لا نحتاج إلى Past Perfect هنا.",
      "لماذا؟",
      "لأن القصة تسير إلى الأمام خطوة بخطوة.",
    ],
  },
  {
    id: "s4",
    num: 4,
    title: "④ 🎥 Past Continuous",
    units: [
      "Past Continuous يصنع المشهد.",
      "مثال:",
      "Leo was sitting near the window.",
      "The wind was blowing.",
      "Birds were singing.",
      "People were walking in the street.",
      "هذه ليست أحداثًا تدفع القصة إلى الأمام بالضرورة.",
      "إنها الخلفية.",
    ],
  },
  {
    id: "s5",
    num: 5,
    title: "⑤ ⏪ Past Perfect",
    units: [
      "Past Perfect يرجع خطوة إلى الوراء.",
      "مثال:",
      "Leo opened the window and realized that someone had broken the glass.",
      "opened",
      "→ الحدث الرئيسي.",
      "realized",
      "→ حدث رئيسي.",
      "had broken",
      "→ حدث وقع قبل لحظة الإدراك.",
      "إذن Past Perfect يعمل مثل فلاش باك.",
    ],
  },
  {
    id: "s6",
    num: 6,
    title: "⑥ ⏪🎥 Past Perfect Continuous",
    units: [
      "Past Perfect Continuous يرجع إلى نشاط كان مستمرًا قبل نقطة ماضية.",
      "مثال:",
      "Leo was tired because he had been working all night.",
      "was tired",
      "→ حالة.",
      "had been working",
      "→ نشاط استمر لفترة قبل ذلك.",
    ],
  },
  {
    id: "s7",
    num: 7,
    title: "⑦ 🕰️ الخط الزمني الكامل",
    units: [
      "لنأخذ مثالًا قويًا:",
      "When Maya arrived at the station, the train had already left. People were waiting for another train, and one man had been standing there for more than an hour.",
      "الترتيب:",
      "① القطار غادر.",
      "② الرجل بدأ الانتظار واستمر لأكثر من ساعة.",
      "③ Maya وصلت.",
      "④ الناس كانوا ينتظرون.",
      "لاحظ أن الزمن لا يعني دائمًا أن الأحداث يمكن وضعها في خط بسيط واحد؛ بعض الأنشطة تتداخل.",
    ],
  },
  {
    id: "s8",
    num: 8,
    title: "⑧ 🧠 لماذا Past Simple مهم جدًا؟",
    units: [
      "لأنه العمود الفقري للقصة.",
      "مثال:",
      "I woke up.",
      "I got dressed.",
      "I ate breakfast.",
      "I left home.",
      "I walked to school.",
      "هذه أحداث متتابعة.",
      "كلها Past Simple.",
    ],
  },
  {
    id: "s9",
    num: 9,
    title: "⑨ 🎥 أضف الخلفية",
    units: [
      "الآن:",
      "I was walking to school when I heard a strange sound.",
      "was walking",
      "→ الخلفية.",
      "heard",
      "→ الحدث.",
      "هذه هي أشهر تركيبة:",
      "Past Continuous + when + Past Simple",
    ],
  },
  {
    id: "s10",
    num: 10,
    title: "⑩ ⏪ أضف Past Perfect",
    units: [
      "الآن:",
      "I was walking to school when I heard a strange sound. I realized that I had left my phone at home.",
      "was walking",
      "→ خلفية.",
      "heard",
      "→ حدث.",
      "realized",
      "→ حدث.",
      "had left",
      "→ حدث أقدم من لحظة الإدراك.",
    ],
  },
  {
    id: "s11",
    num: 11,
    title: "⑪ ⏪🎥 أضف Past Perfect Continuous",
    units: [
      "الآن أصبحت القصة أكثر تعقيدًا:",
      "I was walking to school when I heard a strange sound. I realized that I had left my phone at home. I was tired because I had been walking for forty minutes.",
      "لدينا:",
      "was walking",
      "→ Past Continuous",
      "heard",
      "→ Past Simple",
      "realized",
      "→ Past Simple",
      "had left",
      "→ Past Perfect",
      "was tired",
      "→ Past Simple / حالة",
      "had been walking",
      "→ Past Perfect Continuous",
    ],
  },
  {
    id: "s12",
    num: 12,
    title: "⑫ 🔥 أربع عدسات زمنية",
    units: [
      "فكر بالأزمنة كأنها أربع كاميرات:",
      "📸 Past Simple",
      "→ صورة لحدث.",
      "🎥 Past Continuous",
      "→ فيديو لشيء يحدث.",
      "⏪ Past Perfect",
      "→ رجوع إلى حدث أقدم.",
      "⏪🎥 Past Perfect Continuous",
      "→ رجوع إلى نشاط كان مستمرًا.",
      "هذه الطريقة أقوى من حفظ الجداول.",
    ],
  },
  {
    id: "s13",
    num: 13,
    title: "⑬ 🧠 Past Simple vs Past Perfect",
    units: [
      "قارن:",
      "When I arrived, Sara left.",
      "الترتيب:",
      "I arrived → Sara left.",
      "When I arrived, Sara had left.",
      "الترتيب:",
      "Sara left → I arrived.",
      "إذن:",
      "had",
      "ليست مجرد إضافة شكلية.",
      "إنها قد تغيّر ترتيب الأحداث.",
    ],
  },
  {
    id: "s14",
    num: 14,
    title: "⑭ 🧠 Past Continuous vs Past Perfect Continuous",
    units: [
      "قارن:",
      "I was waiting when the bus arrived.",
      "كنت أنتظر عندما وصلت الحافلة.",
      "التركيز:",
      "ماذا كنت أفعل عند وصول الحافلة؟",
      "I had been waiting for forty minutes when the bus arrived.",
      "كنت أنتظر منذ أربعين دقيقة عندما وصلت الحافلة.",
      "التركيز:",
      "منذ متى كنت أنتظر؟",
    ],
  },
  {
    id: "s15",
    num: 15,
    title: "⑮ 🧠 Past Perfect vs Past Perfect Continuous",
    units: [
      "قارن:",
      "She had cleaned the kitchen before the guests arrived.",
      "التركيز:",
      "المطبخ أصبح نظيفًا.",
      "She had been cleaning the kitchen for two hours before the guests arrived.",
      "التركيز:",
      "كانت عملية التنظيف مستمرة لمدة ساعتين.",
    ],
  },
  {
    id: "s16",
    num: 16,
    title: "⑯ ⭐ قاعدة \"النتيجة أم النشاط؟\"",
    units: [
      "إذا كان التركيز على:",
      "ماذا تم إنجازه؟",
      "→ Past Perfect",
      "إذا كان التركيز على:",
      "ما النشاط الذي كان مستمرًا؟ وكم استمر؟",
      "→ Past Perfect Continuous",
      "مثال:",
      "He had painted the wall.",
      "النتيجة:",
      "الحائط مطلي.",
      "He had been painting the wall for three hours.",
      "التركيز:",
      "عملية الطلاء + المدة.",
    ],
  },
  {
    id: "s17",
    num: 17,
    title: "⑰ 🚨 لا تعتمد على كلمة واحدة",
    units: [
      "هذا مهم جدًا في مستوى IQ200.",
      "مثلاً:",
      "yesterday",
      "لا تعني تلقائيًا Past Simple.",
      "يمكن أن نقول:",
      "I visited my aunt yesterday.",
      "Past Simple.",
      "لكن:",
      "At 8:00 yesterday, I was visiting my aunt.",
      "Past Continuous.",
      "وكذلك:",
      "Before I went to bed yesterday, I had finished my homework.",
      "Past Perfect.",
      "إذن الكلمة الزمنية وحدها لا تختار الزمن.",
      "المعنى هو الذي يختار الزمن.",
    ],
  },
  {
    id: "s18",
    num: 18,
    title: "⑱ 🧠 \"when\" لا يعني زمنًا واحدًا",
    units: [
      "هذه نقطة مهمة جدًا.",
      "مثال:",
      "When I arrived, Tom left.",
      "Past Simple + Past Simple.",
      "When I arrived, Tom was sleeping.",
      "Past Simple + Past Continuous.",
      "When I arrived, Tom had left.",
      "Past Simple + Past Perfect.",
      "When I arrived, Tom had been sleeping for two hours.",
      "Past Simple + Past Perfect Continuous.",
      "إذن:",
      "when لا يحدد الزمن.",
      "المعنى هو الذي يحدد الزمن.",
    ],
  },
  {
    id: "s19",
    num: 19,
    title: "⑲ 🧠 \"while\"",
    units: [
      "while غالبًا ترتبط بنشاط مستمر.",
      "مثال:",
      "While I was studying, my brother was playing video games.",
      "نشاطان مستمران.",
      "While I was walking home, I saw an old friend.",
      "نشاط مستمر + حدث.",
      "While they were eating, someone knocked on the door.",
      "نشاط مستمر + حدث.",
    ],
  },
  {
    id: "s20",
    num: 20,
    title: "⑳ 🧠 before و after",
    units: [
      "يمكن أن نستخدمهما مع أكثر من تركيب.",
      "مثال:",
      "I finished my homework before I watched TV.",
      "Past Simple + Past Simple.",
      "I had finished my homework before I watched TV.",
      "Past Perfect + Past Simple.",
      "كلاهما ممكن بحسب السياق.",
      "لا تحفظ:",
      "before = Past Perfect.",
      "هذا خطأ.",
    ],
  },
  {
    id: "s21",
    num: 21,
    title: "㉑ ⏳ by the time",
    units: [
      "غالبًا نرى:",
      "By the time + Past Simple",
      "ثم Past Perfect للحدث المكتمل قبلها.",
      "مثال:",
      "By the time we arrived, the store had closed.",
      "By the time the game started, the players had warmed up.",
      "By the time I woke up, everyone had left.",
    ],
  },
  {
    id: "s22",
    num: 22,
    title: "㉒ 🧠 already",
    units: [
      "already يمكن أن تساعد في إبراز أن الحدث كان قد اكتمل قبل نقطة ماضية.",
      "مثال:",
      "When we arrived, the concert had already begun.",
    ],
  },
  {
    id: "s23",
    num: 23,
    title: "㉓ 🧠 still",
    units: [
      "still = ما يزال / لا يزال",
      "مثال:",
      "When I arrived, they were still working.",
      "أي أنهم كانوا يعملون وما زالوا في منتصف العمل.",
      "مثال أكثر تعقيدًا:",
      "When I arrived, they had been working for five hours and were still working.",
      "لدينا:",
      "had been working",
      "→ المدة حتى تلك اللحظة.",
      "were still working",
      "→ النشاط كان مستمرًا في تلك اللحظة.",
    ],
  },
  {
    id: "s24",
    num: 24,
    title: "㉔ 🕵️ Grammar Detective",
    units: [
      "اقرأ:",
      "When the rescue team arrived, the villagers were standing near the river. They had been waiting for help for several hours because the water had already reached the main road.",
      "حدد:",
      "arrived",
      "→ Past Simple",
      "were standing",
      "→ Past Continuous",
      "had been waiting",
      "→ Past Perfect Continuous",
      "had reached",
      "→ Past Perfect",
      "التحليل:",
      "وصل الفريق.",
      "كان القرويون واقفين.",
      "كانوا ينتظرون منذ عدة ساعات.",
      "وكانت المياه قد وصلت إلى الطريق قبل وصول الفريق.",
    ],
  },
  {
    id: "s25",
    num: 25,
    title: "㉕ 🧪 اختبار 1 — اختر الزمن",
    units: [
      "① When I entered the room, everyone ______.",
      "A) talked",
      "B) was talking",
      "C) had talked",
      "② When I entered the room, everyone ______ the room before I arrived.",
      "A) had left",
      "B) was leaving",
      "C) leaves",
      "③ She was exhausted because she ______ all morning.",
      "A) had been running",
      "B) ran",
      "C) was run",
      "④ I ______ my homework yesterday.",
      "A) had finished",
      "B) finished",
      "C) was finishing",
      "⑤ At 9:00 last night, I ______ a documentary.",
      "A) watched",
      "B) had watched",
      "C) was watching",
      "الإجابات:",
      "① B",
      "② A",
      "③ A",
      "④ B",
      "⑤ C",
    ],
  },
  {
    id: "s26",
    num: 26,
    title: "㉖ 🧪 اختبار 2 — اختر حسب المعنى",
    units: [
      "1",
      "\"عندما وصلت، كان أحمد ينام.\"",
      "A. Ahmed had slept.",
      "B. Ahmed was sleeping.",
      "C. Ahmed had been sleeping.",
      "الإجابة الأفضل:",
      "B",
      "لأننا نصف ما كان يحدث عند لحظة الوصول.",
      "2",
      "\"عندما وصلت، كان أحمد قد نام.\"",
      "A. Ahmed had slept.",
      "B. Ahmed was sleeping.",
      "C. Ahmed had been sleeping.",
      "الإجابة:",
      "A",
      "التركيز على حدوث النوم قبل وصولي.",
      "3",
      "\"عندما وصلت، كان أحمد نائمًا منذ ساعتين.\"",
      "A. Ahmed was sleeping.",
      "B. Ahmed had slept.",
      "C. Ahmed had been sleeping for two hours.",
      "الإجابة:",
      "C",
      "التركيز على المدة.",
    ],
  },
  {
    id: "s27",
    num: 27,
    title: "㉗ 🧠 IQ200 — لا يوجد زمن واحد \"صحيح\" دائمًا",
    units: [
      "هذه نقطة متقدمة جدًا.",
      "مثال:",
      "When I arrived, they ate dinner.",
      "يمكن أن تكون صحيحة في سياق معين.",
      "لكن إذا قصدت:",
      "\"عندما وصلت، كانوا يتناولون العشاء.\"",
      "الأفضل:",
      "When I arrived, they were eating dinner.",
      "وإذا قصدت:",
      "\"عندما وصلت، كانوا قد تناولوا العشاء.\"",
      "الأفضل:",
      "When I arrived, they had eaten dinner.",
      "وإذا قصدت:",
      "\"عندما وصلت، كانوا قد أمضوا ساعة وهم يتناولون العشاء.\"",
      "يمكن أن نقول:",
      "When I arrived, they had been eating dinner for an hour.",
      "المعنى يحدد الزمن.",
    ],
  },
  {
    id: "s28",
    num: 28,
    title: "㉘ 🔥 IQ200 — ثلاثة أحداث",
    units: [
      "الجملة:",
      "When Nora entered the kitchen, her mother was cooking, her father had already washed the dishes, and her brother had been preparing dessert for an hour.",
      "حلل:",
      "entered",
      "→ حدث رئيسي.",
      "was cooking",
      "→ نشاط مستمر عند وصول Nora.",
      "had already washed",
      "→ غسل الصحون اكتمل قبل وصولها.",
      "had been preparing",
      "→ تحضير الحلوى كان مستمرًا لمدة ساعة قبل وصولها.",
      "هذه جملة واحدة، لكنها تحتوي على أربع علاقات زمنية مختلفة.",
    ],
  },
  {
    id: "s29",
    num: 29,
    title: "㉙ 🧠 كيف تختار الزمن خلال ثانيتين؟",
    units: [
      "استخدم هذه الخوارزمية:",
      "الخطوة 1",
      "هل هو حدث ماضٍ عادي؟",
      "نعم → Past Simple.",
      "الخطوة 2",
      "هل كان يحدث في لحظة معينة؟",
      "نعم → Past Continuous.",
      "الخطوة 3",
      "هل حدث قبل حدث ماضٍ آخر؟",
      "نعم → Past Perfect.",
      "الخطوة 4",
      "هل كان مستمرًا لفترة قبل حدث ماضٍ آخر؟",
      "نعم → Past Perfect Continuous.",
    ],
  },
  {
    id: "s30",
    num: 30,
    title: "㉚ ⚔️ Boss Battle — اكتشف الزمن من القصة",
    units: [
      "اقرأ:",
      "\"At 7:30 yesterday, Sam was driving home. He had finished work an hour earlier. He had been working since early morning, so he was exhausted. While he was driving, his phone rang.\"",
      "حدد كل زمن:",
      "was driving",
      "→ Past Continuous",
      "had finished",
      "→ Past Perfect",
      "had been working",
      "→ Past Perfect Continuous",
      "was",
      "→ Past Simple من verb to be",
      "was driving",
      "→ Past Continuous",
      "rang",
      "→ Past Simple",
    ],
  },
  {
    id: "s31",
    num: 31,
    title: "㉛ 🧠 خط الزمن",
    units: [
      "يمكن رسم القصة:",
      "بدأ العمل",
      "↓",
      "استمر العمل",
      "↓",
      "انتهى العمل",
      "↓",
      "بعد ساعة",
      "↓",
      "Sam was driving",
      "↓",
      "phone rang",
      "↓",
      "NOW",
      "وهنا:",
      "had been working",
      "→ المدة والنشاط.",
      "had finished",
      "→ الحدث الأقدم المكتمل.",
      "was driving",
      "→ الخلفية.",
      "rang",
      "→ الحدث المفاجئ.",
    ],
  },
  {
    id: "s32",
    num: 32,
    title: "㉜ 🧪 اختبار 3 — صحح الأخطاء",
    units: [
      "صحح:",
      "① I had been studied for three hours.",
      "② She was waiting for two hours when he arrived.",
      "③ When we arrived, the movie had started already.",
      "④ He had went home before I called.",
      "⑤ They had been knowing each other for ten years.",
      "⑥ Did you had finished your work?",
      "الإجابات:",
      "① I had been studying for three hours.",
      "② I had been waiting for two hours when he arrived.",
      "لكن انتبه:",
      "إذا كان المقصود فقط \"كنت أنتظر عندما وصل\":",
      "I was waiting when he arrived.",
      "أما إذا أردنا مدة ساعتين:",
      "I had been waiting for two hours when he arrived.",
      "③ When we arrived, the movie had already started.",
      "④ He had gone home before I called.",
      "⑤ They had known each other for ten years.",
      "⑥ Had you finished your work?",
    ],
  },
  {
    id: "s33",
    num: 33,
    title: "㉝ 🚀 IQ200 — السؤال الخادع",
    units: [
      "اختر:",
      "When I arrived, Sarah ______ for an hour.",
      "A) studied",
      "B) was studying",
      "C) had been studying",
      "أفضل إجابة:",
      "C",
      "لماذا؟",
      "لأن:",
      "for an hour",
      "توضح مدة امتدت حتى نقطة ماضية.",
      "لكن:",
      "When I arrived, Sarah ______.",
      "هنا يمكن أن تكون:",
      "was studying",
      "إذا كان التركيز على ما كانت تفعله لحظة وصولي.",
    ],
  },
  {
    id: "s34",
    num: 34,
    title: "㉞ 🧠 سؤال أصعب",
    units: [
      "اختر:",
      "When I arrived, Sarah ______ the report.",
      "A) finished",
      "B) was finishing",
      "C) had finished",
      "D) had been finishing",
      "كل واحدة يمكن أن تعطي معنى مختلفًا في سياق مناسب.",
      "لكن إذا كان المعنى:",
      "\"كانت قد أنهت التقرير قبل وصولي.\"",
      "→ C",
      "إذا كان المعنى:",
      "\"كانت في عملية إنهاء التقرير عندما وصلت.\"",
      "→ B",
      "إذا كان المعنى:",
      "\"كانت تعمل على إنهاء التقرير لفترة قبل وصولي.\"",
      "→ D",
      "وهنا يظهر الفرق الحقيقي بين الأزمنة:",
      "الزمن ليس مجرد قاعدة؛ إنه زاوية نظر إلى الحدث.",
    ],
  },
  {
    id: "s35",
    num: 35,
    title: "㉟ 🧠 مستوى متقدم: focus",
    units: [
      "هذه كلمة مهمة:",
      "focus = التركيز",
      "نفس الحدث يمكن أن ننظر إليه من زوايا مختلفة.",
      "مثال:",
      "He painted the house.",
      "التركيز:",
      "الإنجاز.",
      "He was painting the house.",
      "التركيز:",
      "النشاط في تلك اللحظة.",
      "He had painted the house.",
      "التركيز:",
      "الإنجاز قبل نقطة ماضية.",
      "He had been painting the house for three hours.",
      "التركيز:",
      "النشاط والمدة قبل نقطة ماضية.",
    ],
  },
  {
    id: "s36",
    num: 36,
    title: "㊱ 🎬 تمرين القصة السينمائية",
    units: [
      "اقرأ:",
      "When Lina entered the old library, several students were searching through the shelves. The librarian had already locked one of the rooms because someone had broken a window. Lina noticed that the students had been searching for almost an hour. Suddenly, a loud noise came from upstairs.",
      "حدد:",
      "were searching",
      "→ Past Continuous",
      "had already locked",
      "→ Past Perfect",
      "had broken",
      "→ Past Perfect",
      "had been searching",
      "→ Past Perfect Continuous",
      "noticed",
      "→ Past Simple",
      "came",
      "→ Past Simple",
    ],
  },
  {
    id: "s37",
    num: 37,
    title: "㊲ 🧠 لماذا هذه القصة قوية؟",
    units: [
      "لأن كل زمن له وظيفة:",
      "Past Simple",
      "→ يحرك القصة.",
      "Past Continuous",
      "→ يصف المشهد.",
      "Past Perfect",
      "→ يشرح ما حدث قبل نقطة القصة.",
      "Past Perfect Continuous",
      "→ يشرح نشاطًا استمر لفترة قبل نقطة القصة.",
      "وهذه بالضبط الطريقة التي تستخدم بها الأزمنة في الكتابة الحقيقية.",
    ],
  },
  {
    id: "s38",
    num: 38,
    title: "㊳ 🏆 FINAL BOSS",
    units: [
      "أكمل القصة:",
      "\"When the firefighters arrived...\"",
      "يجب أن تستخدم:",
      "① Past Simple",
      "② Past Continuous",
      "③ Past Perfect",
      "④ Past Perfect Continuous",
      "مثال هيكل فقط:",
      "When the firefighters arrived, people were standing outside the building. The fire had already reached the second floor, and several firefighters had been preparing their equipment for several minutes. Then...",
      "أكمل القصة بنفسك.",
    ],
  },
  {
    id: "s39",
    num: 39,
    title: "㊴ 🏆 الاختبار النهائي",
    units: [
      "اختر أفضل إجابة:",
      "① When I got home, my sister ______ dinner.",
      "A) cooked",
      "B) was cooking",
      "C) had cooked",
      "D) had been cooking",
      "المعنى العادي \"كانت تطبخ\":",
      "B",
      "② When I got home, my sister ______ dinner before I arrived.",
      "A) cooked",
      "B) was cooking",
      "C) had cooked",
      "D) had been cooking",
      "المعنى:",
      "كانت قد أنهت الطبخ قبل وصولي.",
      "→ C",
      "③ When I got home, my sister ______ dinner for two hours.",
      "A) cooked",
      "B) was cooking",
      "C) had cooked",
      "D) had been cooking",
      "→ D",
      "④ By the time we arrived, the show ______.",
      "A) started",
      "B) was starting",
      "C) had started",
      "D) had been starting",
      "→ C",
      "⑤ I was tired because I ______ all day.",
      "A) worked",
      "B) was working",
      "C) had worked",
      "D) had been working",
      "→ D",
      "⑥ We ______ to the museum yesterday.",
      "A) went",
      "B) had gone",
      "C) were going",
      "D) had been going",
      "→ A",
      "⑦ At 6:00 yesterday, we ______ dinner.",
      "A) ate",
      "B) had eaten",
      "C) were eating",
      "D) had been eating",
      "→ C",
      "⑧ Before the teacher arrived, the students ______ the classroom.",
      "A) cleaned",
      "B) were cleaning",
      "C) had cleaned",
      "D) had been cleaned",
      "→ C",
    ],
  },
  {
    id: "s40",
    num: 40,
    title: "㊵ 🧠 التحدي الأكبر",
    units: [
      "اكتب 12 جملة عن يوم غامض حدث في الماضي.",
      "يجب أن تستخدم:",
      "✅ 4 Past Simple",
      "✅ 3 Past Continuous",
      "✅ 3 Past Perfect",
      "✅ 2 Past Perfect Continuous",
      "ويجب أن تتضمن:",
      "when",
      "while",
      "before",
      "after",
      "by the time",
      "for",
      "since",
      "already",
    ],
  },
  {
    id: "summary",
    title: "🧠 الملخص النهائي",
    units: [
      "📸 Past Simple",
      "حدث ماضٍ.",
      "I opened the door.",
      "🎥 Past Continuous",
      "حدث كان مستمرًا في لحظة ماضية.",
      "I was opening the door when the phone rang.",
      "⏪ Past Perfect",
      "حدث اكتمل قبل حدث ماضٍ آخر.",
      "I had opened the door before the phone rang.",
      "⏪🎥 Past Perfect Continuous",
      "نشاط استمر لفترة قبل حدث ماضٍ آخر.",
      "I had been waiting for an hour before the bus arrived.",
    ],
  },
  {
    id: "golden",
    title: "🏆 القاعدة الذهبية الكبرى",
    units: [
      "لا تحفظ الأزمنة كأنها أربع جزر منفصلة.",
      "فكر بالقصة:",
      "📸 ماذا حدث؟",
      "→ Past Simple",
      "🎥 ماذا كان يحدث؟",
      "→ Past Continuous",
      "⏪ ماذا كان قد حدث قبل ذلك؟",
      "→ Past Perfect",
      "⏪🎥 ماذا كان مستمرًا لفترة قبل ذلك؟",
      "→ Past Perfect Continuous",
    ],
  },
  {
    id: "final",
    title: "🚀 IQ200 FINAL CHALLENGE",
    units: [
      "حلل هذه الجملة:",
      "\"When the scientist entered the laboratory, the assistants were checking the equipment. They had already completed the first test, but they had been working on the second test for nearly three hours. Suddenly, one of the machines stopped.\"",
      "الإجابة:",
      "① entered",
      "→ Past Simple",
      "→ حدث وصول العالم.",
      "② were checking",
      "→ Past Continuous",
      "→ ما كان يحدث لحظة وصوله.",
      "③ had already completed",
      "→ Past Perfect",
      "→ الاختبار الأول اكتمل قبل وصوله.",
      "④ had been working",
      "→ Past Perfect Continuous",
      "→ العمل على الاختبار الثاني كان مستمرًا لمدة ثلاث ساعات تقريبًا.",
      "⑤ stopped",
      "→ Past Simple",
      "→ حدث مفاجئ دفع القصة إلى الأمام.",
      "وهنا أصبح لدينا نظام الماضي كاملًا:",
      "📸 الحدث → 🎥 الخلفية → ⏪ الحدث الأقدم → ⏪🎥 النشاط الأقدم المستمر",
      "وهذه نقطة مهمة جدًا في المنهج، لأننا من هنا لن نتعامل مع الأزمنة كقواعد منفصلة فقط، بل سنبدأ باستخدامها لبناء قصص، حوارات، مواقف، ووصف أحداث حقيقية بمستوى أعلى بكثير.",
    ],
  },
];

export const SOURCE_NUMBERED_COUNT = 40;
export const SOURCE_LEDGER_COUNT = SOURCE_SECTIONS.length;

export const SEC: Record<string, number> = SOURCE_SECTIONS.reduce<Record<string, number>>(
  (acc, s, i) => {
    acc[s.id] = i;
    return acc;
  },
  {}
);

export function unitsOf(id: string): string[] {
  return SOURCE_SECTIONS[SEC[id]].units;
}

// ============================================================
// الأزمنة الأربعة — تعريف مركزي للمختبرات
// ============================================================
export type Tense30 = "Past Simple" | "Past Continuous" | "Past Perfect" | "Past Perfect Continuous";

export const TENSES_30: { tense: Tense30; emoji: string; ar: string; question: string }[] = [
  { tense: "Past Simple", emoji: "📸", ar: "حدث ماضٍ", question: "ماذا حدث؟" },
  { tense: "Past Continuous", emoji: "🎥", ar: "نشاط مستمر في لحظة ماضية", question: "ماذا كان يحدث؟" },
  { tense: "Past Perfect", emoji: "⏪", ar: "حدث اكتمل قبل حدث ماضٍ آخر", question: "ماذا كان قد حدث قبل ذلك؟" },
  { tense: "Past Perfect Continuous", emoji: "⏪🎥", ar: "نشاط استمر لفترة قبل حدث ماضٍ آخر", question: "ماذا كان مستمرًا لفترة قبل ذلك؟" },
];

// ============================================================
// مختبر المحقق — الأفعال وأزمنتها (من المصدر حرفيًا)
// ============================================================
export type DetectiveItem30 = { verb: string; tense: Tense30; role?: string };

export const DETECTIVE_RESCUE_30: DetectiveItem30[] = [
  { verb: "arrived", tense: "Past Simple", role: "وصل الفريق." },
  { verb: "were standing", tense: "Past Continuous", role: "كان القرويون واقفين." },
  { verb: "had been waiting", tense: "Past Perfect Continuous", role: "كانوا ينتظرون منذ عدة ساعات." },
  { verb: "had reached", tense: "Past Perfect", role: "وكانت المياه قد وصلت إلى الطريق قبل وصول الفريق." },
];

export const DETECTIVE_SAM_30: DetectiveItem30[] = [
  { verb: "was driving", tense: "Past Continuous", role: "الخلفية." },
  { verb: "had finished", tense: "Past Perfect", role: "الحدث الأقدم المكتمل." },
  { verb: "had been working", tense: "Past Perfect Continuous", role: "المدة والنشاط." },
  { verb: "was", tense: "Past Simple", role: "Past Simple من verb to be" },
  { verb: "rang", tense: "Past Simple", role: "الحدث المفاجئ." },
];

export const DETECTIVE_LINA_30: DetectiveItem30[] = [
  { verb: "were searching", tense: "Past Continuous" },
  { verb: "had already locked", tense: "Past Perfect" },
  { verb: "had broken", tense: "Past Perfect" },
  { verb: "had been searching", tense: "Past Perfect Continuous" },
  { verb: "noticed", tense: "Past Simple" },
  { verb: "came", tense: "Past Simple" },
];

export const DETECTIVE_NORA_30: DetectiveItem30[] = [
  { verb: "entered", tense: "Past Simple", role: "حدث رئيسي." },
  { verb: "was cooking", tense: "Past Continuous", role: "نشاط مستمر عند وصول Nora." },
  { verb: "had already washed", tense: "Past Perfect", role: "غسل الصحون اكتمل قبل وصولها." },
  { verb: "had been preparing", tense: "Past Perfect Continuous", role: "تحضير الحلوى كان مستمرًا لمدة ساعة قبل وصولها." },
];

export const DETECTIVE_FINAL_30: DetectiveItem30[] = [
  { verb: "entered", tense: "Past Simple", role: "حدث وصول العالم." },
  { verb: "were checking", tense: "Past Continuous", role: "ما كان يحدث لحظة وصوله." },
  { verb: "had already completed", tense: "Past Perfect", role: "الاختبار الأول اكتمل قبل وصوله." },
  { verb: "had been working", tense: "Past Perfect Continuous", role: "العمل على الاختبار الثاني كان مستمرًا لمدة ثلاث ساعات تقريبًا." },
  { verb: "stopped", tense: "Past Simple", role: "حدث مفاجئ دفع القصة إلى الأمام." },
];

// ============================================================
// تمارين المصدر — أسئلة الاختيار (حرفية من المصدر)
// ============================================================
export type SourceMcq30 = { q: string; opts: string[]; answer: number; note?: string };

export const QUIZ1_30: SourceMcq30[] = [
  { q: "① When I entered the room, everyone ______.", opts: ["A) talked", "B) was talking", "C) had talked"], answer: 1 },
  { q: "② When I entered the room, everyone ______ the room before I arrived.", opts: ["A) had left", "B) was leaving", "C) leaves"], answer: 0 },
  { q: "③ She was exhausted because she ______ all morning.", opts: ["A) had been running", "B) ran", "C) was run"], answer: 0 },
  { q: "④ I ______ my homework yesterday.", opts: ["A) had finished", "B) finished", "C) was finishing"], answer: 1 },
  { q: "⑤ At 9:00 last night, I ______ a documentary.", opts: ["A) watched", "B) had watched", "C) was watching"], answer: 2 },
];

export const QUIZ2_30: SourceMcq30[] = [
  {
    q: "\"عندما وصلت، كان أحمد ينام.\"",
    opts: ["A. Ahmed had slept.", "B. Ahmed was sleeping.", "C. Ahmed had been sleeping."],
    answer: 1,
    note: "لأننا نصف ما كان يحدث عند لحظة الوصول.",
  },
  {
    q: "\"عندما وصلت، كان أحمد قد نام.\"",
    opts: ["A. Ahmed had slept.", "B. Ahmed was sleeping.", "C. Ahmed had been sleeping."],
    answer: 0,
    note: "التركيز على حدوث النوم قبل وصولي.",
  },
  {
    q: "\"عندما وصلت، كان أحمد نائمًا منذ ساعتين.\"",
    opts: ["A. Ahmed was sleeping.", "B. Ahmed had slept.", "C. Ahmed had been sleeping for two hours."],
    answer: 2,
    note: "التركيز على المدة.",
  },
];

/** ㉜ تصحيح الأخطاء — الجملة الخاطئة + التصحيح الحرفي من المصدر + خيارات منصّة. */
export type ErrorFix30 = {
  wrong: string;
  /** خيارات التصحيح (خيار المصدر الصحيح + مشتتات منصّة). */
  opts: string[];
  answer: number;
  /** ملاحظة المصدر إن وجدت. */
  sourceNote?: string[];
};

export const ERRORS_30: ErrorFix30[] = [
  {
    wrong: "① I had been studied for three hours.",
    opts: ["I had been studying for three hours.", "I had been study for three hours.", "I was been studying for three hours."],
    answer: 0,
  },
  {
    wrong: "② She was waiting for two hours when he arrived.",
    opts: ["I had been waiting for two hours when he arrived.", "She was waited for two hours when he arrived.", "She waiting for two hours when he arrived."],
    answer: 0,
    sourceNote: [
      "لكن انتبه:",
      "إذا كان المقصود فقط \"كنت أنتظر عندما وصل\":",
      "I was waiting when he arrived.",
      "أما إذا أردنا مدة ساعتين:",
      "I had been waiting for two hours when he arrived.",
    ],
  },
  {
    wrong: "③ When we arrived, the movie had started already.",
    opts: ["When we arrived, the movie had already started.", "When we arrived, the movie already have started.", "When we arrived, the movie was started already."],
    answer: 0,
  },
  {
    wrong: "④ He had went home before I called.",
    opts: ["He had gone home before I called.", "He had going home before I called.", "He has went home before I called."],
    answer: 0,
  },
  {
    wrong: "⑤ They had been knowing each other for ten years.",
    opts: ["They had known each other for ten years.", "They had been known each other for ten years.", "They were knowing each other for ten years."],
    answer: 0,
  },
  {
    wrong: "⑥ Did you had finished your work?",
    opts: ["Had you finished your work?", "Did you have finished your work?", "Have you had finished your work?"],
    answer: 0,
  },
];

export const FINAL_EXAM_30: SourceMcq30[] = [
  {
    q: "① When I got home, my sister ______ dinner.",
    opts: ["A) cooked", "B) was cooking", "C) had cooked", "D) had been cooking"],
    answer: 1,
    note: "المعنى العادي \"كانت تطبخ\": B",
  },
  {
    q: "② When I got home, my sister ______ dinner before I arrived.",
    opts: ["A) cooked", "B) was cooking", "C) had cooked", "D) had been cooking"],
    answer: 2,
    note: "المعنى: كانت قد أنهت الطبخ قبل وصولي. → C",
  },
  {
    q: "③ When I got home, my sister ______ dinner for two hours.",
    opts: ["A) cooked", "B) was cooking", "C) had cooked", "D) had been cooking"],
    answer: 3,
  },
  {
    q: "④ By the time we arrived, the show ______.",
    opts: ["A) started", "B) was starting", "C) had started", "D) had been starting"],
    answer: 2,
  },
  {
    q: "⑤ I was tired because I ______ all day.",
    opts: ["A) worked", "B) was working", "C) had worked", "D) had been working"],
    answer: 3,
  },
  {
    q: "⑥ We ______ to the museum yesterday.",
    opts: ["A) went", "B) had gone", "C) were going", "D) had been going"],
    answer: 0,
  },
  {
    q: "⑦ At 6:00 yesterday, we ______ dinner.",
    opts: ["A) ate", "B) had eaten", "C) were eating", "D) had been eating"],
    answer: 2,
  },
  {
    q: "⑧ Before the teacher arrived, the students ______ the classroom.",
    opts: ["A) cleaned", "B) were cleaning", "C) had cleaned", "D) had been cleaned"],
    answer: 2,
  },
];

// ============================================================
// التحدي الأكبر ㊵ + FINAL BOSS ㊳ — متطلبات المحلل الكتابي
// ============================================================
export const CHALLENGE_WORDS_30 = ["when", "while", "before", "after", "by the time", "for", "since", "already"] as const;

export const BOSS_STARTER_30 = "When the firefighters arrived...";

// ============================================================
// منطقة الاختبارات — 20 سؤالًا جديدًا مؤلفة خصيصًا لهذا الاختبار
// (ليست منسوخة من تمارين المصدر ولا إعادة صياغة مباشرة لها)
// ============================================================
export type TestQ30 =
  | { n: number; type: "single"; ar: string; en?: string; opts: string[]; answer: number; why: string; trap?: string }
  | { n: number; type: "tf"; ar: string; en?: string; answer: boolean; why: string; trap?: string }
  | { n: number; type: "multi"; ar: string; en?: string; opts: string[]; answer: number[]; why: string; trap?: string }
  | { n: number; type: "order"; ar: string; en?: string; items: string[]; answer: string[]; why: string; trap?: string }
  | { n: number; type: "match"; ar: string; en?: string; left: string[]; right: string[]; answer: number[]; why: string; trap?: string }
  | { n: number; type: "spot"; ar: string; segments: string[]; answer: number; fix: string; why: string; trap?: string };

export const TEST_30: TestQ30[] = [
  {
    n: 1, type: "single",
    ar: "أكمل بما يناسب المعنى: «عندما دخلتُ الصف، كان المعلم يشرح الدرس».",
    en: "When I entered the classroom, the teacher ______ the lesson.",
    opts: ["explained", "was explaining", "had explained", "had been explaining"],
    answer: 1,
    why: "المطلوب وصف نشاط كان مستمرًا لحظة الدخول (ماذا كان يحدث؟) — وهذا دور Past Continuous: was explaining.",
    trap: "had explained تعني أن الشرح انتهى قبل دخولي — معنى مختلف تمامًا.",
  },
  {
    n: 2, type: "single",
    ar: "أكمل: «عندما انتهى الفيلم، كنا جالسين في السينما منذ ثلاث ساعات».",
    en: "When the movie ended, we ______ in the cinema for three hours.",
    opts: ["sat", "were sitting", "had been sitting", "had sat"],
    answer: 2,
    why: "for three hours مدة امتدت حتى نقطة ماضية (نهاية الفيلم) — نشاط + مدة قبل حدث ماضٍ = Past Perfect Continuous.",
    trap: "were sitting تصف اللحظة فقط ولا تُبرز المدة الممتدة حتى تلك النقطة.",
  },
  {
    n: 3, type: "tf",
    ar: "في الجملة التالية، مغادرة نورا حدثت قبل وصولي.",
    en: "When I arrived, Nora had left.",
    answer: true,
    why: "had left هي Past Perfect — فلاش باك إلى حدث أقدم: نورا غادرت أولًا ثم وصلتُ أنا.",
    trap: "بدون had (Nora left) ينقلب الترتيب: وصلتُ أولًا ثم غادرت.",
  },
  {
    n: 4, type: "tf",
    ar: "كلمة yesterday تفرض دائمًا استخدام Past Simple.",
    answer: false,
    why: "الكلمة الزمنية وحدها لا تختار الزمن — المعنى هو الذي يختار. يمكن أن نقول At 8:00 yesterday, I was visiting my aunt. (ماضٍ مستمر) مع yesterday.",
    trap: "حفظ «كلمة = زمن» هو عكس فكرة آلة اختيار الزمن.",
  },
  {
    n: 5, type: "multi",
    ar: "اختر كل الجمل الصحيحة نحويًا (أكثر من إجابة).",
    opts: [
      "He had gone home before I called him.",
      "They had been knowing the answer for years.",
      "Had you finished the project by noon?",
      "I had been studied all night.",
    ],
    answer: [0, 2],
    why: "بعد had يأتي V3 (gone)، والسؤال يبدأ بـ Had + فاعل + V3. أما know فهو فعل حالة لا يُستخدم عادة بصيغة been knowing، وstudied بعد had been خطأ لأن الصيغة تحتاج verb-ing.",
    trap: "had been + V3 خلط بين صيغتي Past Perfect و Past Perfect Continuous.",
  },
  {
    n: 6, type: "order",
    ar: "رتّب الأحداث من الأقدم إلى الأحدث كما تفهمها من الجملة.",
    en: "Rami had finished dinner before he watched the film, and after the film he went to bed.",
    items: ["Rami watched the film", "Rami went to bed", "Rami finished dinner"],
    answer: ["Rami finished dinner", "Rami watched the film", "Rami went to bed"],
    why: "had finished + before تعني أن العشاء اكتمل أولًا، ثم الفيلم، وafter the film تضع النوم آخرًا.",
    trap: "ترتيب الكلمات في الجملة ليس ترتيب الأحداث — الصيغ والروابط هي الدليل.",
  },
  {
    n: 7, type: "match",
    ar: "طابق كل جملة مع زمنها.",
    left: [
      "The children played in the garden.",
      "The children were playing when it started to rain.",
      "The children had played before lunch.",
      "The children had been playing for an hour when their mother called.",
    ],
    right: ["Past Simple", "Past Continuous", "Past Perfect", "Past Perfect Continuous"],
    answer: [0, 1, 2, 3],
    why: "played حدث ماضٍ، were playing نشاط مستمر في لحظة ماضية، had played اكتمل قبل الغداء، had been playing نشاط بمدة قبل نقطة ماضية (اتصال الأم).",
    trap: "الجملة الثانية فيها started أيضًا — لكن المطلوب زمن فعل الأطفال (were playing).",
  },
  {
    n: 8, type: "single",
    ar: "أي جملة تركّز على «النتيجة / الإنجاز» وليس على النشاط والمدة؟",
    opts: [
      "Salma had been writing the report for two hours.",
      "Salma had written the report.",
      "Salma was writing the report.",
    ],
    answer: 1,
    why: "had written (Past Perfect) تركّز على أن التقرير أصبح مكتوبًا — الإنجاز. أما had been writing فتركّز على عملية الكتابة ومدتها.",
    trap: "قاعدة «النتيجة أم النشاط؟»: إنجاز → Past Perfect، نشاط + مدة → Past Perfect Continuous.",
  },
  {
    n: 9, type: "single",
    ar: "أكمل: «في الساعة العاشرة ليلة أمس، كان فادي يقرأ رواية».",
    en: "At 10:00 last night, Fadi ______ a novel.",
    opts: ["read", "was reading", "had read", "had been read"],
    answer: 1,
    why: "ساعة محددة في الماضي + نشاط مستمر عندها = Past Continuous: was reading.",
    trap: "At 10:00 لا تعني تلقائيًا Past Simple — نحن داخل لحظة ممتدة، لا ننقل حدثًا مكتملًا.",
  },
  {
    n: 10, type: "spot",
    ar: "اضغط على الجزء الخاطئ في الجملة.",
    segments: ["She", "had", "went", "home", "before the rain started."],
    answer: 2,
    fix: "had gone — بعد had يأتي التصريف الثالث V3 وليس V2.",
    why: "go → went → gone. بعد had نستخدم gone دائمًا، لأن went هي صيغة الماضي البسيط.",
    trap: "had + V2 من أشهر الأخطاء المتقدمة في نظام الماضي.",
  },
  {
    n: 11, type: "spot",
    ar: "اضغط على الجزء الخاطئ في الجملة.",
    segments: ["They", "had been", "wait", "for the doctor", "since 9:00."],
    answer: 2,
    fix: "waiting — صيغة Past Perfect Continuous هي had been + verb-ing.",
    why: "بعد had been يأتي الفعل بصيغة -ing دائمًا: had been waiting.",
    trap: "نسيان -ing بعد been يكسر الصيغة حتى لو كان المعنى صحيحًا.",
  },
  {
    n: 12, type: "single",
    ar: "لديك حدثان: «القطار غادر. ثم وصلتُ أنا.» — اختر الجملة الواحدة التي تنقل هذا الترتيب بدقة.",
    en: "The train left. Then I arrived.",
    opts: [
      "When I arrived, the train left.",
      "When I arrived, the train had left.",
      "When the train left, I had arrived.",
    ],
    answer: 1,
    why: "الحدث الأقدم (مغادرة القطار) يأخذ Past Perfect: had left، والحدث الأحدث (وصولي) يبقى Past Simple.",
    trap: "الخيار الأول يعكس الترتيب: يعني أن القطار غادر بعد وصولي.",
  },
  {
    n: 13, type: "tf",
    ar: "الجملة التالية تصف نشاطين مستمرين في الوقت نفسه.",
    en: "While I was cooking, my sister was studying.",
    answer: true,
    why: "while + Past Continuous في الجزأين = نشاطان مستمران متوازيان في الماضي.",
    trap: "while ترتبط غالبًا بالاستمرارية — لكنها قد تأتي أيضًا مع نشاط مستمر + حدث.",
  },
  {
    n: 14, type: "single",
    ar: "فسّر السبب: «لماذا كانت هالة منهكة؟ لأنها كانت تحمل الصناديق طوال الصباح».",
    en: "Hala was exhausted because she ______ boxes all morning.",
    opts: ["carried", "was carrying", "had been carrying", "had carried"],
    answer: 2,
    why: "الإنهاك نتيجة نشاط استمر لفترة قبل تلك اللحظة الماضية — نشاط + مدة قبل نقطة ماضية = had been carrying.",
    trap: "had carried ممكنة نحويًا لكنها تُبرز الإنجاز لا النشاط الذي سبّب التعب.",
  },
  {
    n: 15, type: "multi",
    ar: "أي العناصر التالية تدعم اختيار Past Perfect Continuous؟ (أكثر من إجابة)",
    opts: [
      "مدة صريحة مع for",
      "نقطة بداية مع since",
      "نشاط كان مستمرًا قبل نقطة ماضية",
      "حدث واحد مكتمل بلا أي امتداد",
    ],
    answer: [0, 1, 2],
    why: "Past Perfect Continuous = نشاط امتد لفترة (for/since) قبل حدث ماضٍ آخر. الحدث الواحد المكتمل بلا امتداد هو Past Simple.",
    trap: "وجود for وحدها لا يكفي — يجب أن تمتد المدة حتى نقطة ماضية.",
  },
  {
    n: 16, type: "single",
    ar: "أكمل الجزء الذي يأتي بعد by the time: «بحلول وصول المعلمة إلى الصف، كان الطلاب قد خبّؤوا الهدية».",
    en: "By the time the teacher ______ the classroom, the students had hidden the surprise gift.",
    opts: ["entered", "had entered", "was entering", "had been entering"],
    answer: 0,
    why: "النمط الشائع: By the time + Past Simple، ثم Past Perfect للحدث الذي اكتمل قبلها — الدخول هو النقطة المرجعية فيبقى بسيطًا.",
    trap: "وضع had في الجزأين يفقد الجملة نقطتها المرجعية.",
  },
  {
    n: 17, type: "match",
    ar: "طابق كل كلمة زمنية مع استخدامها الصحيح في جملة.",
    left: ["already", "still", "for", "since"],
    right: [
      "The lecture had already begun when we entered.",
      "At midnight, the engineers were still working.",
      "She had been painting for six hours.",
      "He had been living there since 2019.",
    ],
    answer: [0, 1, 2, 3],
    why: "already تُبرز الاكتمال قبل نقطة ماضية، still تعني أن النشاط ما يزال مستمرًا، for للمدة، since لنقطة البداية.",
    trap: "for تسبق مدة (six hours) بينما since تسبق نقطة بداية (2019) — لا تخلط بينهما.",
  },
  {
    n: 18, type: "order",
    ar: "رتّب أحداث القصة القصيرة من الأقدم إلى الأحدث.",
    en: "Dana won the race. She had been training for months, and after the race she celebrated with her team.",
    items: ["Dana celebrated with her team", "Dana trained for months", "Dana won the race"],
    answer: ["Dana trained for months", "Dana won the race", "Dana celebrated with her team"],
    why: "had been training نشاط سبق السباق وامتد شهورًا، ثم الفوز (Past Simple)، ثم الاحتفال (after the race).",
    trap: "الجملة تبدأ بالفوز لكن الصيغة had been training تكشف أن التدريب أقدم.",
  },
  {
    n: 19, type: "single",
    ar: "نريد أن نقول إن الكلب مزّق الأريكة قبل وصولنا إلى البيت — اختر الصيغة الصحيحة.",
    en: "When we got home, the dog ______ the sofa.",
    opts: ["tore", "was tearing", "had torn", "had been torn"],
    answer: 2,
    why: "التمزيق اكتمل قبل الوصول (حدث أقدم من حدث ماضٍ آخر) = Past Perfect: had torn.",
    trap: "tore تعني أن التمزيق حدث بعد وصولنا أو عنده — ترتيب مختلف.",
  },
  {
    n: 20, type: "single",
    ar: "اختر الترجمة الأدق: «عندما اتصلتُ بها، كانت سلمى تذاكر منذ الصباح».",
    opts: [
      "Salma was studying when I called her.",
      "Salma had studied when I called her.",
      "Salma had been studying since morning when I called her.",
    ],
    answer: 2,
    why: "«منذ الصباح» نقطة بداية لنشاط استمر حتى لحظة الاتصال — since + نشاط ممتد قبل نقطة ماضية = Past Perfect Continuous.",
    trap: "was studying تهمل المدة، وhad studied تجعل المذاكرة منتهية قبل الاتصال.",
  },
];

// ============================================================
// منطقة المعلم — خلف كلمة المرور somer173
// ============================================================
export const TEACHER_PASSWORD_30 = "somer173";

export const TEACHER_30_OVERVIEW = {
  title: "Lesson Overview — نظرة عامة",
  objectives: [
    "أن يميّز الطالب الأزمنة الأربعة (Past Simple / Past Continuous / Past Perfect / Past Perfect Continuous) من المعنى لا من الكلمات المحفوظة.",
    "أن يقرأ قصة ويحدد زمن كل فعل فيها، ويرسم خطًا زمنيًا لعدة أحداث.",
    "أن يستخدم when / while / before / after / by the time / already / still / for / since بشكل صحيح.",
    "أن يعرف متى يكون Past Perfect ضروريًا ومتى لا نحتاجه، والفرق بين النتيجة والنشاط والمدة.",
    "أن يكتشف الأخطاء المتقدمة ويدمج الأزمنة الأربعة في قصة واحدة.",
    "أن يتعامل مع أسئلة IQ200 التي يتغير جوابها بتغير المعنى المقصود.",
  ],
  prerequisites: [
    "الدرس 27 — Past Perfect (had + V3).",
    "الدرس 28 — Past Perfect vs Past Simple.",
    "الدرس 29 — Past Perfect Continuous (had been + verb-ing).",
    "Past Simple و Past Continuous والفرق بينهما (الدروس السابقة).",
  ],
  core: [
    "هذا درس مراجعة وتثبيت — لا زمن جديد؛ الهدف بناء «نظام تحكم» يختار الزمن من المعنى.",
    "آلة الأسئلة الأربعة: حدث؟ → PS · مستمر عند لحظة؟ → PC · قبل حدث آخر؟ → PP · مستمر لفترة قبل حدث آخر؟ → PPC.",
    "العدسات الأربع: 📸 صورة · 🎥 فيديو · ⏪ فلاش باك · ⏪🎥 فلاش باك مستمر.",
  ],
} as const;

export type TeacherNote30 = { head: string; lines: string[] };

export const TEACHER_30_NOTES: TeacherNote30[] = [
  { head: "فلسفة الدرس — مراجعة نظام لا قواعد منفصلة", lines: ["هذا الدرس لا يضيف زمنًا جديدًا؛ إنه يدمج أربعة أزمنة في نظام واحد.", "درّب الطالب على السؤال قبل القاعدة: ماذا حدث؟ ماذا كان يحدث؟ ماذا كان قد حدث؟ ماذا كان مستمرًا قبل ذلك؟"] },
  { head: "آلة اختيار الزمن (القسمان ② و㉙)", lines: ["اجعل الطالب يمرّ على الأسئلة الأربعة بالترتيب مع كل جملة جديدة.", "الهدف أن يصل زمن القرار إلى ثانيتين — التكرار الشفهي مفيد جدًا هنا."] },
  { head: "العمود الفقري والخلفية (③–⑪)", lines: ["Past Simple يحرّك القصة إلى الأمام، وPast Continuous يرسم المشهد خلفها.", "قصة المشي إلى المدرسة (⑨–⑪) تُبنى طبقة فوق طبقة — اطلب من الطالب تسمية وظيفة كل فعل قبل كشف الإجابة."] },
  { head: "had تقلب الترتيب (⑬)", lines: ["Sara left مقابل Sara had left — نفس الكلمات تقريبًا وترتيب أحداث معاكس.", "درّب على السؤال: من حدث أولًا؟ قبل أي شيء آخر."] },
  { head: "النتيجة أم النشاط؟ (⑭–⑯ و㉟)", lines: ["إنجاز/نتيجة → Past Perfect؛ نشاط + مدة → Past Perfect Continuous.", "استخدم أمثلة الحائط المطلي والمطبخ النظيف — صورة النتيجة مقابل فيديو العملية."] },
  { head: "لا كلمة تحسم الزمن (⑰–⑱)", lines: ["yesterday تأتي مع ثلاثة أزمنة مختلفة في المصدر — اعرضها جنبًا إلى جنب.", "when تأتي مع الأزمنة الأربعة كلها — المعنى هو الحكم الوحيد."] },
  { head: "كلمات الربط (⑲–㉓)", lines: ["while غالبًا مع الاستمرارية، وbefore/after تصحّ مع البسيط أو التام بحسب السياق — لا تحفظ before = Past Perfect.", "by the time + Past Simple ثم Past Perfect للمكتمل قبلها.", "already تُبرز الاكتمال، وstill تُبرز الاستمرار — ويمكن جمعهما مع had been working في جملة واحدة (㉓)."] },
  { head: "أسئلة IQ200 (㉗ ㉝ ㉞)", lines: ["نقطة متقدمة حساسة: قد تكون أكثر من إجابة صحيحة نحويًا — والمعنى المقصود هو الذي يرجّح.", "في ㉞ كل خيار من B/C/D يعطي معنى مختلفًا — ناقش المعاني الثلاثة ولا تختصرها في إجابة واحدة.", "الرسالة الكبرى: الزمن زاوية نظر إلى الحدث، وليس قاعدة صماء."] },
  { head: "المحقق النحوي (㉔ ㉚ ㊱ والتحدي النهائي)", lines: ["اطلب تحديد زمن كل فعل ثم وظيفته القصصية (يحرك القصة / يصف المشهد / فلاش باك / نشاط ممتد).", "في قصة Sam لاحظ أن was وحدها Past Simple من verb to be — نقطة يغفل عنها الطلاب."] },
];

export type TeacherSolution30 = { head: string; lines: string[] };

export const TEACHER_30_SOLUTIONS: TeacherSolution30[] = [
  { head: "㉕ اختبار 1 — اختر الزمن", lines: ["① B — was talking: نشاط مستمر لحظة الدخول.", "② A — had left: المغادرة اكتملت قبل الوصول (before I arrived).", "③ A — had been running: نشاط ممتد سبّب الإنهاك.", "④ B — finished: حدث ماضٍ واحد مع yesterday بلا مقارنة.", "⑤ C — was watching: ساعة محددة + نشاط مستمر عندها."] },
  { head: "㉖ اختبار 2 — اختر حسب المعنى", lines: ["1 → B (Ahmed was sleeping): نصف ما كان يحدث عند لحظة الوصول.", "2 → A (Ahmed had slept): التركيز على حدوث النوم قبل وصولي.", "3 → C (had been sleeping for two hours): التركيز على المدة.", "وجّه الطالب: الجمل العربية الثلاث متشابهة جدًا — الفرق كله في «كان ينام / كان قد نام / نائم منذ ساعتين»."] },
  { head: "㉜ اختبار 3 — صحح الأخطاء", lines: ["① I had been studying for three hours — بعد had been يأتي verb-ing.", "② I had been waiting for two hours when he arrived — مع ملاحظة المصدر: لو قصدنا «كنت أنتظر عندما وصل» فقط تكفي I was waiting when he arrived؛ المدة تستدعي had been waiting. (المصدر ينتقل من She إلى I في التصحيح — حافظنا عليه حرفيًا.)", "③ When we arrived, the movie had already started — موضع already بين had والفعل.", "④ He had gone home before I called — V3 بعد had.", "⑤ They had known each other for ten years — know فعل حالة.", "⑥ Had you finished your work? — مساعد واحد فقط، لا did مع had."] },
  { head: "㉝ السؤال الخادع", lines: ["C — had been studying: for an hour مدة امتدت حتى نقطة ماضية.", "لكن بدون for an hour تصبح was studying صحيحة إذا كان التركيز على اللحظة — ناقش الحالتين."] },
  { head: "㉞ سؤال أصعب", lines: ["«كانت قد أنهت قبل وصولي» → C (had finished).", "«كانت في عملية الإنهاء عندما وصلت» → B (was finishing).", "«كانت تعمل على الإنهاء لفترة قبل وصولي» → D (had been finishing).", "A (finished) ممكنة في سياق تتابعي: وصلتُ ثم أنهت.", "الهدف التربوي: لا تسأل «ما الإجابة الصحيحة؟» بل «ما المعنى المقصود؟»."] },
  { head: "㉔ المحقق — فريق الإنقاذ", lines: ["arrived → Past Simple · were standing → Past Continuous · had been waiting → Past Perfect Continuous · had reached → Past Perfect.", "التحليل: وصل الفريق، كان القرويون واقفين، كانوا ينتظرون منذ ساعات، وكانت المياه قد وصلت قبل وصول الفريق."] },
  { head: "㉚ Boss Battle — قصة Sam", lines: ["was driving → PC · had finished → PP · had been working → PPC · was → PS من verb to be · rang → PS.", "اربطها بخط الزمن في ㉛: بدأ العمل → استمر → انتهى → بعد ساعة → كان يقود → رن الهاتف → NOW."] },
  { head: "㊱ القصة السينمائية — Lina", lines: ["were searching → PC · had already locked → PP · had broken → PP · had been searching → PPC · noticed → PS · came → PS.", "اربطها بـ ㊲: كل زمن له وظيفة — يحرك القصة / يصف المشهد / يشرح ما قبل النقطة / يشرح نشاطًا ممتدًا."] },
  { head: "🚀 FINAL CHALLENGE — المختبر", lines: ["entered → PS (وصول العالم) · were checking → PC (لحظة وصوله) · had already completed → PP (الاختبار الأول اكتمل قبله) · had been working → PPC (ثلاث ساعات تقريبًا) · stopped → PS (حدث مفاجئ).", "الخلاصة: 📸 الحدث → 🎥 الخلفية → ⏪ الحدث الأقدم → ⏪🎥 النشاط الأقدم المستمر."] },
];

export const TEACHER_30_RUBRICS: TeacherNote30[] = [
  {
    head: "㊳ FINAL BOSS — سلّم تقييم إكمال قصة الإطفائيين",
    lines: [
      "البداية الإلزامية: When the firefighters arrived...",
      "يجب أن تظهر الأزمنة الأربعة: Past Simple + Past Continuous + Past Perfect + Past Perfect Continuous.",
      "هيكل المصدر مثال فقط — لا يُقبل نسخه حرفيًا كإجابة.",
      "قيّم: وضوح الحدث الرئيسي، خلفية مشهدية واحدة على الأقل، فلاش باك واحد على الأقل، نشاط ممتد بمدة واحدة على الأقل.",
      "الخصم الأكبر لأخطاء الصيغة: had + V2، وhad been بدون verb-ing.",
    ],
  },
  {
    head: "㊵ التحدي الأكبر — سلّم تقييم «يوم غامض»",
    lines: [
      "الطول: 12 جملة عن يوم غامض حدث في الماضي.",
      "التوزيع الإلزامي: 4 Past Simple · 3 Past Continuous · 3 Past Perfect · 2 Past Perfect Continuous.",
      "الكلمات الإلزامية الثماني: when · while · before · after · by the time · for · since · already.",
      "تحقق أن ترتيب الأحداث قابل للاستخراج من الصيغ لا من ترتيب الجمل فقط.",
      "محلّل الكتابة في الدرس يفحص الأنماط آليًا، لكن مراجعة المعنى تبقى دور المعلم.",
    ],
  },
];

export const TEACHER_30_MISTAKES: TeacherNote30[] = [
  { head: "had + V2", lines: ["مثل had went — بعد had يأتي V3 فقط: had gone (القسم ㉜-④)."] },
  { head: "had been + V3 أو بدون -ing", lines: ["مثل had been studied / had been wait — الصيغة: had been + verb-ing (القسم ㉜-①)."] },
  { head: "أفعال الحالة مع الاستمرارية", lines: ["had been knowing ✗ → had known ✓ — know فعل حالة (القسم ㉜-⑤)."] },
  { head: "did + had", lines: ["Did you had finished? ✗ → Had you finished? ✓ — مساعد واحد فقط (القسم ㉜-⑥)."] },
  { head: "موضع already", lines: ["had started already (في سياق المصدر) → had already started — بين had والفعل (القسم ㉜-③)."] },
  { head: "الاعتماد على كلمة واحدة", lines: ["yesterday / when / before لا تحسم الزمن وحدها — المعنى يحسم (الأقسام ⑰ ⑱ ⑳)."] },
  { head: "إجبار Past Perfect", lines: ["سلسلة أحداث متتابعة تبقى Past Simple (③ ⑧) — لا نحتاج had إلا عند الرجوع خطوة للوراء."] },
  { head: "خلط النتيجة بالنشاط", lines: ["had painted (نتيجة) مقابل had been painting for three hours (نشاط + مدة) — القسمان ⑯ و㉟."] },
];
