// ============================================================
// بنك الاختبارات النهائية (Final Test Bank) — طبقة نهاية الدرس
//
// القاعدة الدائمة: كل درس — الحالي والمستقبلي — ينتهي باختبار نهائي
// من 12 إلى 15 سؤالًا (الأفضل 15) على محتوى الدرس نفسه، بنفس نموذج
// src/shared/finalTest.tsx. الأسئلة كلها من إعداد المنصة (اختبار تقييمي
// على محتوى الدرس)، ولا تنقل محتوى المصدر ولا تعدّله.
//
// أضف درسًا جديدًا بإضافة مفتاحه هنا ثم اعرض <LessonFinalTest lesson={n} />
// في نهاية خطوات الدرس. التدقيق الآلي scripts/audit-final-test.mjs يتحقق
// من: الوجود، الموقع في نهاية الدرس، عدد الأسئلة، وجود الإجابات والشروح،
// وعدم تكرار الاختبار.
// ============================================================

import type { FinalTestQuestion } from "./finalTest";

/** حدود عدد أسئلة الاختبار النهائي — يتغير العدد بإضافة أسئلة مع كل تطوير */
export const FINAL_TEST_MIN = 12;
export const FINAL_TEST_MAX = 15;

// ------------------------------------------------------------
// الدرس 27 — Past Perfect (الماضي التام)
// ------------------------------------------------------------
const LESSON_27: FinalTestQuestion[] = [
  {
    type: "single",
    ar: "ما الصيغة الصحيحة لتكوين Past Perfect؟",
    options: ["had + V3", "have + V3", "was + V-ing", "did + V1"],
    answer: 0,
    why: "الصيغة الثابتة هي Subject + had + V3، وكلمة had نفسها لا تتغير مع أي ضمير.",
    concept: "تكوين Past Perfect",
    trap: "استخدام have مع الماضي، أو تغيير had حسب الضمير (he had / they had نفس الشكل).",
  },
  {
    type: "tf",
    ar: "جملة: «had لا تتغير مع الضمائر I / he / they» — هل هي صحيحة؟",
    en: "He had left. · They had left. · I had left.",
    answer: true,
    why: "had واحدة لكل الضمائر في Past Perfect، بخلاف have/has في Present Perfect.",
    concept: "ثبات had مع كل الضمائر",
    trap: "كتابة «he haved» أو «they has» اعتمادًا على قواعد المضارع.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["The train", " had ", "went", " before we arrived."],
    answer: 2,
    why: "بعد had نستخدم V3 لا V2، والصحيح هو gone وليس went.",
    concept: "V2 مقابل V3 بعد had",
    trap: "الاعتماد على شكل V2 لأنه «الماضي الذي حفظناه».",
  },
  {
    type: "single",
    ar: "أكمل:",
    en: "By the time we arrived, she ____ the film.",
    options: ["watched", "had watched", "has watched", "watches"],
    answer: 1,
    why: "by the time + نقطة ماضية ⇒ الحدث المكتمل قبلها يأتي بـ Past Perfect (had + V3).",
    concept: "ترتيب حدثين في الماضي (by the time)",
    trap: "استخدام Past Simple أو Present Perfect مع by the time + نقطة ماضية.",
  },
  {
    type: "order",
    ar: "رتّب الجملة بشكل صحيح:",
    items: ["The film", "had", "already", "started", "before we arrived."],
    why: "had + already + V3 ثم جملة before بماضٍ بسيط.",
    concept: "ترتيب عناصر جملة Past Perfect",
    trap: "وضع already بعد الفعل مباشرة بدل موضعه بين had و V3.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة الصحيحة (start — V3):",
    before: "By the time we got to the cinema, the film",
    after: "",
    accept: ["had started", "had already started"],
    why: "by the time تشير إلى أن الفيلم بدأ قبل وصولنا ⇒ had + V3.",
    concept: "by the time + Past Perfect",
    trap: "استخدام started وحدها لأن by the time تظهر كأنها ظرف عادي.",
  },
  {
    type: "match",
    ar: "صِل الكلمة بمعناها:",
    pairs: [
      { left: "before", right: "قبل" },
      { left: "after", right: "بعد" },
      { left: "by the time", right: "بحلول الوقت الذي" },
      { left: "never", right: "أبدًا" },
    ],
    why: "هذه أدوات الربط والظروف التي تظهر كثيرًا مع Past Perfect.",
    concept: "كلمات Past Perfect المهمة",
    trap: "الخلط بين before و by the time في تحديد من الأقدم.",
  },
  {
    type: "multi",
    ar: "اختر كل الجمل الصحيحة نحويًا:",
    options: [
      "I had finished my homework.",
      "He had went home.",
      "They hadn't eaten anything.",
      "Had you seen it before?",
      "She have had left.",
    ],
    answers: [0, 2, 3],
    why: "الصحيح: had + V3 (I had finished) · النفي hadn't + V3 (They hadn't eaten) · السؤال بتقديم had على الفاعل (Had you seen it before?). والخاطئ: «He had went» لأن بعد had نحتاج V3 (gone)، و«She have had left» لأن have و had لا يجتمعان.",
    concept: "الإثبات والنفي والسؤال",
    trap: "الخلط بين V2 و V3 في الجمل الخاطئة.",
  },
  {
    type: "tf",
    ar: "الفكرة الأساسية: Past Perfect = حدث أقدم من حدث ماضٍ آخر.",
    answer: true,
    why: "الفكرة ليست «زمنًا جديدًا» بل ترتيبًا: حدث أقدم + حدث أحدث في الماضي.",
    concept: "الفكرة الذهبية",
    trap: "تفسير Past Perfect كأنه زمن جديد لا علاقة له بالترتيب.",
  },
  {
    type: "single",
    ar: "أي صيغة سؤال صحيحة في Past Perfect؟",
    options: ["Had + subject + V3?", "Did + subject + had + V3?", "Have + subject + V3?", "Was + subject + V3?"],
    answer: 0,
    why: "نقدّم had على الفاعل، ويبقى الفعل في صيغة V3.",
    concept: "سؤال Past Perfect",
    trap: "استخدام did مع had في نفس السؤال.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["She", " hadn't", " ate", " anything."],
    answer: 2,
    why: "بعد hadn't يبقى الفعل V3، والصحيح eaten.",
    concept: "النفي hadn't + V3",
    trap: "تصحيح النفي إلى ate لأن الصيغة تبدو أخفّ في النطق.",
  },
  {
    type: "tf",
    ar: "Past Perfect تعني دائمًا أن الحدث وقع منذ زمن طويل جدًا.",
    answer: false,
    why: "المعنى مرتبط بوجود حدث ماضٍ آخر بعده، لا بمدة القِدَم — قد يفصل بينهما دقائق فقط.",
    concept: "خرافة «القديم جدًا»",
    trap: "ربط Past Perfect بمدة زمنية طويلة تلقائيًا.",
  },
  {
    type: "order",
    ar: "رتّب أجزاء الجملة:",
    items: ["By the time", "the guests arrived,", "we", "had already cooked dinner."],
    why: "by the time + ماضٍ بسيط في الجملة الثانية، والأقدم يأتي بـ had already + V3.",
    concept: "ربط by the time بالحدث الأقدم",
    trap: "جعل العشاء هو الحدث الأحدث.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة الصحيحة (buy):",
    before: "By the time we arrived, Sarah",
    after: "the tickets.",
    accept: ["had bought", "had already bought"],
    why: "شراء التذاكر سبق وصولنا ⇒ had + V3.",
    concept: "ترتيب الأحداث في القصة",
    trap: "استخدام bought وحدها.",
  },
  {
    type: "single",
    ar: "في الجملة الآتية، أي حدث وقع أولًا؟",
    en: "When I arrived at the door, Emma had already left.",
    options: ["Emma left first.", "I arrived first.", "Both happened together.", "Nothing happened first."],
    answer: 0,
    why: "had left تعني أن المغادرة أقدم، ووصولي بعدها.",
    concept: "تمييز الحدث الأقدم",
    trap: "الاعتماد على ترتيب الكلمات في الجملة بدل معنى had.",
  },
];

// ------------------------------------------------------------
// الدرس 28 — Past Perfect vs Past Simple
// ------------------------------------------------------------
const LESSON_28: FinalTestQuestion[] = [
  {
    type: "single",
    ar: "عندما يكون في الماضي حدثان: الحدث الأقدم يُصاغ بـ…",
    options: ["Past Perfect", "Past Simple", "Present Perfect", "Present Simple"],
    answer: 0,
    why: "Past Perfect هو الذي يرجع خطوة للوراء قبل الحدث المذكور بـ Past Simple.",
    concept: "قاعدة الترتيب",
    trap: "الاعتماد على ترتيب الجملة لا على ترتيب الأحداث.",
  },
  {
    type: "tf",
    ar: "Past Simple = حدث وقع وانتهى، و Past Perfect = حدث قبله.",
    en: "I visited the museum. / I had visited the museum before you called.",
    answer: true,
    why: "الأول سرد لحدث مكتمل، والثاني مرجع خلفي قبل حدث ماضٍ آخر.",
    concept: "الفرق الأساسي",
    trap: "استخدام Past Perfect لكل حدث ماضٍ بلا سبب.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["When we arrived,", " the movie", " already", " started."],
    answer: 3,
    why: "الفيلم بدأ قبل وصولنا ⇒ had already started.",
    concept: "الحدث الأقدم في بداية المشهد",
    trap: "استخدام started لأن الفعل مكتوب في الماضي فعلًا.",
  },
  {
    type: "single",
    ar: "أكمل:",
    en: "By the time you called, I ____ the museum.",
    options: ["visited", "had visited", "have visited", "was visiting"],
    answer: 1,
    why: "by the time + نقطة ماضية ⇒ المرجع الخلفي بـ Past Perfect (had + V3).",
    concept: "by the time + Past Perfect",
    trap: "اختيار visited لأن by the time تبدو مجرد ترتيب، وهي في الدرس من أقوى إشارات الماضي التام.",
  },
  {
    type: "match",
    ar: "صِل الزمن بمعناه:",
    pairs: [
      { left: "Past Simple", right: "حدث وقع وانتهى" },
      { left: "Past Perfect", right: "حدث قبل حدث ماضٍ آخر" },
      { left: "Past Continuous", right: "كان يحدث لحظة معينة" },
      { left: "Past Perfect Continuous", right: "استمر مدة قبل نقطة ماضية" },
    ],
    why: "هذه هي العدسات الأربع التي تُبنى عليها المقارنة.",
    concept: "عدسات الزمن الماضي",
    trap: "دمج Past Perfect مع Past Continuous في الاستخدام.",
  },
  {
    type: "multi",
    ar: "اختر كل الجمل التي تصف سردًا متتابعًا (لا تحتاج Past Perfect):",
    options: [
      "I woke up, drank coffee, and left.",
      "The plane had taken off before I arrived.",
      "She visited her aunt yesterday.",
      "He had never seen the sea before that trip.",
    ],
    answers: [0, 2],
    why: "السرد المتتابع يبقى بسيطًا (woke / drank / left · visited)، والمقارنة تحتاج Past Perfect.",
    concept: "sequence مقابل back reference",
    trap: "تحويل كل فعل في السرد المتتابع إلى Past Perfect.",
  },
  {
    type: "tf",
    ar: "لا نستخدم Past Perfect لمجرد أن الحدث قديم.",
    answer: true,
    why: "نستخدمه لوجود حدث ماضٍ لاحق في الجملة أو القصة، لا لمجرد القِدَم.",
    concept: "خرافة «لأنه قديم جدًا»",
    trap: "إضافة had إلى جملة ماضية لا يوجد فيها حدث لاحق.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة الصحيحة (take off):",
    before: "When I arrived at the airport, the plane",
    after: "",
    accept: ["had already taken off", "had taken off already", "had taken off"],
    why: "الإقلاع سبق وصولي ⇒ had + V3.",
    concept: "ترتيب الحدثين",
    trap: "تغيير had إلى was.",
  },
  {
    type: "order",
    ar: "رتّب الجملة:",
    items: ["The plane", "had", "already", "taken off", "when I arrived."],
    why: "had + already + V3 + جملة when بالماضي البسيط.",
    concept: "بناء الجملة",
    trap: "وضع taken off قبل already.",
  },
  {
    type: "single",
    ar: "في الجملة الآتية، ما زمن «were running»؟",
    en: "When I arrived, the plane had taken off and people were running.",
    options: ["Past Simple", "Past Continuous", "Past Perfect", "Past Perfect Continuous"],
    answer: 1,
    why: "were running تصف ما كان يحدث لحظة وصولي، فهي الخلفية.",
    concept: "ثلاثة أحداث في الماضي",
    trap: "تحويل الخلفية إلى Past Perfect.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["The movie", " had", " already", " began", " when we arrived."],
    answer: 3,
    why: "بعد had نستخدم V3، والصحيح begun.",
    concept: "V3 للأفعال غير المنتظمة",
    trap: "استخدام V2 مع had.",
  },
  {
    type: "tf",
    ar: "«back reference» تعني الرجوع خطوة للوراء: حدث قبل الحدث الذي نتحدث عنه.",
    answer: true,
    why: "هذا هو الاستخدام الذي يجعل Past Perfect ضروريًا في القصة.",
    concept: "back reference",
    trap: "الخلط بين المرجع الخلفي والسرد المتتابع.",
  },
  {
    type: "single",
    ar: "أي عبارة تصف Past Perfect بدقة؟",
    options: [
      "الرجوع خطوة إلى الوراء قبل الحدث المذكور",
      "سرد الأحداث بالترتيب",
      "وصف ما كان يحدث لحظة معينة",
      "وصف عادة متكررة في الماضي",
    ],
    answer: 0,
    why: "هذه الصورة (خطوة للوراء) هي التي تحل كل تدريبات المقارنة.",
    concept: "صورة الزمن",
    trap: "وصفه بأنه مجرد «ماضٍ أقدم» بلا علاقة بالجملة الحالية.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة الصحيحة (finish):",
    before: "By the time she went out, she",
    after: "her homework.",
    accept: ["had finished", "had already finished"],
    why: "by the time + نقطة ماضية ⇒ الحدث المكتمل قبلها had + V3.",
    concept: "by the time + Past Perfect",
    trap: "استخدام finished وحدها بعد by the time.",
  },
  {
    type: "match",
    ar: "صِل الجملة بزمنها:",
    pairs: [
      { left: "I visited the museum.", right: "Past Simple" },
      { left: "I was visiting the museum when you called.", right: "Past Continuous" },
      { left: "I had visited the museum before you called.", right: "Past Perfect" },
    ],
    why: "الفرق بين الجمل الثلاث هو الفرق بين الأزمنة الثلاثة.",
    concept: "ثلاث جمل وعصورها",
    trap: "الحكم من الكلمة المفتاحية وحدها بدل المعنى.",
  },
];

// ------------------------------------------------------------
// الدرس 29 — Past Perfect Continuous
// ------------------------------------------------------------
const LESSON_29: FinalTestQuestion[] = [
  {
    type: "single",
    ar: "ما صيغة Past Perfect Continuous؟",
    options: ["had been + V-ing", "had + V3", "was + V-ing", "have been + V-ing"],
    answer: 0,
    why: "الشريط: had + been + verb-ing، و had لا تتغير مع الضمائر.",
    concept: "تكوين الزمن",
    trap: "إسقاط been أو استخدام was بدل had.",
  },
  {
    type: "tf",
    ar: "I had been studying. تعني: نشاط استمر مدة قبل نقطة في الماضي.",
    answer: true,
    why: "الزمن يصف الاستمرارية والمدة قبل نقطة ماضية، لا مجرد حدث منتهٍ.",
    concept: "معنى الزمن",
    trap: "معاملته كأنه مجرد نسخة طويلة من Past Perfect.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["They", " had", " been", " wait", " for two hours."],
    answer: 3,
    why: "بعد had been يأتي الفعل بصيغة V-ing، والصحيح waiting.",
    concept: "الصيغة بعد been",
    trap: "استخدام المصدر بعد been.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة المستمرة الصحيحة (study):",
    before: "She",
    after: "for three hours when her brother interrupted her.",
    accept: ["had been studying"],
    why: "مدة ماضية قبل نقطة معينة (when her brother interrupted) ⇒ had been + V-ing.",
    concept: "المدة قبل نقطة ماضية",
    trap: "استخدام had studied وإسقاط فكرة الاستمرارية.",
  },
  {
    type: "single",
    ar: "أكمل النفي:",
    en: "She ____ waiting when the bus arrived.",
    options: ["hadn't been", "hadn't", "didn't been", "wasn't been"],
    answer: 0,
    why: "النفي: hadn't been + V-ing.",
    concept: "النفي",
    trap: "إسقاط been أو استخدام didn't مع been.",
  },
  {
    type: "order",
    ar: "رتّب الجملة:",
    items: ["The villagers", "had", "been", "waiting", "for several hours", "when the rescue team arrived."],
    why: "لاحظ: الفاعل + had + been + V-ing + المدة، ثم نقطة الماضي في النهاية.",
    concept: "بناء جملة كاملة",
    trap: "وضع المدة بعد when.",
  },
  {
    type: "match",
    ar: "صِل الكلمة بوظيفتها:",
    pairs: [
      { left: "for", right: "المدة" },
      { left: "since", right: "نقطة البداية" },
      { left: "How long", right: "السؤال عن المدة" },
      { left: "had been + V-ing", right: "نشاط مستمر قبل نقطة ماضية" },
    ],
    why: "هذه هي أدوات الزمن الأربع التي يتكرر استخدامها معه.",
    concept: "أدوات المدة",
    trap: "تبديل for و since.",
  },
  {
    type: "multi",
    ar: "اختر كل الجمل الصحيحة:",
    options: [
      "I had been reading for an hour.",
      "She had been knew him.",
      "Had you been waiting long?",
      "They hadn't been sleeping well.",
    ],
    answers: [0, 2, 3],
    why: "الصحيح had been + V-ing في الإثبات والنفي والسؤال.",
    concept: "صحّة الصيغة في كل الأشكال",
    trap: "استخدام V2 بعد been.",
  },
  {
    type: "single",
    ar: "أي صيغة سؤال صحيحة؟",
    options: ["Had you been studying?", "Did you had been studying?", "Have you had been studying?"],
    answer: 0,
    why: "نقدّم had على الفاعل ويبقى been + V-ing.",
    concept: "السؤال",
    trap: "إضافة did إلى had.",
  },
  {
    type: "tf",
    ar: "نستخدم هذا الزمن مع for و since للتعبير عن مدة قبل نقطة في الماضي.",
    answer: true,
    why: "for مع المدة، و since مع نقطة البداية، والمدة كلها قبل النقطة الماضية.",
    concept: "المدة والاستمرارية",
    trap: "استخدامه مع مدة في الحاضر.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["She", " was been", " studying", " for three hours."],
    answer: 1,
    why: "was been غير صحيحة: الفعل المساعد في Past Perfect Continuous هو had ⇒ had been studying.",
    concept: "الفعل المساعد had لا was",
    trap: "استبدال had بـ was كما في Past Continuous (was studying).",
  },
  {
    type: "single",
    ar: "ما الفرق بين:",
    en: "I had studied. / I had been studying.",
    options: [
      "الأول: اكتمل قبل نقطة ماضية · الثاني: استمر مدة قبل نقطة ماضية",
      "لا فرق بينهما",
      "الأول للمضارع والثاني للماضي",
    ],
    answer: 0,
    why: "الأول نتيجة مكتملة، والثاني يركّز على النشاط ومدته.",
    concept: "الفرق بين Past Perfect و PPC",
    trap: "اعتبار الصيغتين مترادفتين.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة المستمرة الصحيحة (work):",
    before: "The team",
    after: "on the project for months before it launched.",
    accept: ["had been working"],
    why: "مدة ممتدة قبل الإطلاق ⇒ had been + V-ing.",
    concept: "المدة قبل نقطة ماضية",
    trap: "استخدام had worked.",
  },
  {
    type: "tf",
    ar: "كل جملة فيها for يجب أن تكون Past Perfect Continuous.",
    answer: false,
    why: "for نفسها لا تحدد الزمن؛ المهم هل النشاط مستمر وممتد قبل نقطة ماضية أم لا.",
    concept: "لا تعتمد على كلمة واحدة",
    trap: "الاعتماد على for ككلمة مفتاحية مطلقة.",
  },
  {
    type: "match",
    ar: "صِل الجملة بزمنها:",
    pairs: [
      { left: "I studied.", right: "Past Simple" },
      { left: "I was studying.", right: "Past Continuous" },
      { left: "I had studied.", right: "Past Perfect" },
      { left: "I had been studying.", right: "Past Perfect Continuous" },
    ],
    why: "نفس الفعل بأربع عدسات يكشف الفرق بين الأزمنة الأربعة.",
    concept: "العدسات الأربع",
    trap: "الخلط بين Past Perfect و Past Perfect Continuous.",
  },
];

// ------------------------------------------------------------
// الدرس 30 — مراجعة شاملة لنظام الماضي
// ------------------------------------------------------------
const LESSON_30: FinalTestQuestion[] = [
  {
    type: "match",
    ar: "صِل السؤال بالزمن الذي يجيب عنه:",
    pairs: [
      { left: "ماذا حدث؟", right: "Past Simple" },
      { left: "ماذا كان يحدث؟", right: "Past Continuous" },
      { left: "ماذا كان قد حدث قبل ذلك؟", right: "Past Perfect" },
      { left: "ماذا كان مستمرًا لفترة قبل ذلك؟", right: "Past Perfect Continuous" },
    ],
    why: "أربعة أسئلة = أربع عدسات، وهي آلة اختيار الزمن في هذا الدرس.",
    concept: "آلة اختيار الزمن",
    trap: "حفظ القواعد منفصلة بلا ربط بالمعنى.",
  },
  {
    type: "tf",
    ar: "لا تعتمد على كلمة واحدة لتحديد الزمن.",
    answer: true,
    why: "المعنى وترتيب الأحداث هما الحاسمان، والكلمات مجرد إشارات مساعدة.",
    concept: "قاعدة عدم الاعتماد على كلمة واحدة",
    trap: "اختيار الزمن لمجرد وجود for أو already.",
  },
  {
    type: "single",
    ar: "أكمل:",
    en: "When the phone rang, I ____ TV.",
    options: ["watched", "was watching", "had watched", "had been watched"],
    answer: 1,
    why: "ما كان يحدث لحظة الرنين ⇒ Past Continuous.",
    concept: "الخلفية لحظة الحدث",
    trap: "استخدام Past Simple لأن الرنين حدث منتهٍ.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["The assistants", " were", " check", " the equipment."],
    answer: 2,
    why: "بعد were يأتي V-ing: checking.",
    concept: "صيغة Past Continuous",
    trap: "إسقاط ing بعد was/were.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة المستمرة الصحيحة (work):",
    before: "They had already completed the first test, but they",
    after: "on the second test for nearly three hours.",
    accept: ["had been working"],
    why: "مدة ممتدة (three hours) قبل لحظة في الماضي ⇒ Past Perfect Continuous.",
    concept: "المدة قبل نقطة ماضية",
    trap: "استخدام had worked.",
  },
  {
    type: "order",
    ar: "رتّب الجملة:",
    items: ["He", "had been working", "since early morning,", "so he", "was exhausted."],
    why: "النشاط المستمر بمدة (had been working since early morning) هو سبب النتيجة الماضية (was exhausted).",
    concept: "المدة قبل نقطة ماضية",
    trap: "فصل النتيجة «so he was exhausted» عن سببها أو تقديم المدة على النشاط.",
  },
  {
    type: "tf",
    ar: "Past Perfect Continuous يوضح المدة أو الاستمرارية قبل نقطة ماضية.",
    answer: true,
    why: "هذا هو الفرق الجوهري بينه وبين Past Perfect.",
    concept: "الفرق بين العدستين",
    trap: "استخدامه لحدث مكتمل بلا مدة.",
  },
  {
    type: "single",
    ar: "في الجملة الآتية، ما زمن الفعل «stopped»؟",
    en: "Suddenly, one of the machines stopped.",
    options: ["Past Simple", "Past Continuous", "Past Perfect", "Past Perfect Continuous"],
    answer: 0,
    why: "حدث مفاجئ وقع في لحظة ⇒ Past Simple.",
    concept: "الحدث المفاجئ",
    trap: "تحويله إلى Past Continuous لأن القصة فيها خلفية.",
  },
  {
    type: "multi",
    ar: "اختر كل الجمل الصحيحة:",
    options: [
      "I had opened the door before the phone rang.",
      "She had been waiting for an hour.",
      "He had went home.",
      "We had already finished.",
    ],
    answers: [0, 1, 3],
    why: "الصيغتان had + V3 و had been + V-ing صحيحتان، وكان يجب تصحيح went إلى gone.",
    concept: "صيغ الزمن الماضي",
    trap: "الخلط بين V2 و V3.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["Sarah", " had", " been", " study", " all night."],
    answer: 3,
    why: "بعد had been نستخدم V-ing: studying.",
    concept: "الصيغة",
    trap: "نسيان ing بعد been.",
  },
  {
    type: "match",
    ar: "صِل الإشارة بما تدل عليه عادةً:",
    pairs: [
      { left: "while + خلفية مستمرة", right: "Past Continuous" },
      { left: "already + حدث مكتمل قبل حدث", right: "Past Perfect" },
      { left: "for + مدة مستمرة قبل نقطة", right: "Past Perfect Continuous" },
      { left: "then + سرد متتابع", right: "Past Simple" },
    ],
    why: "الإشارات تساعد لكن المعنى يبقى الحاكم.",
    concept: "الإشارات والمعنى",
    trap: "اعتبار الإشارة قانونًا ثابتًا.",
  },
  {
    type: "single",
    ar: "أي زمن يُستخدم غالبًا كخلفية لما كان يحدث لحظة الحدث؟",
    options: ["Past Continuous", "Past Simple", "Past Perfect", "Present Perfect"],
    answer: 0,
    why: "الخلفية المستمرة لحظة الحدث = Past Continuous.",
    concept: "الخلفية في المشهد",
    trap: "استخدام Past Perfect لأن الخلفية «قبل» المشهد.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة الصحيحة (open):",
    before: "By the time the phone rang, I",
    after: "the door.",
    accept: ["had opened", "had already opened"],
    why: "فتح الباب اكتمل قبل الرنين ⇒ had + V3.",
    concept: "الحدث الأقدم (by the time)",
    trap: "استخدام opened وحدها بعد by the time.",
  },
  {
    type: "single",
    ar: "في جملة:",
    en: "When the scientist entered the laboratory, the assistants were checking the equipment.",
    options: [
      "تصف ما كان يحدث لحظة وصوله",
      "تصف حدثًا سبق وصوله",
      "تصف سردًا متتابعًا للأحداث",
    ],
    answer: 0,
    why: "were checking خلفية المشهد في لحظة الدخول (Past Continuous).",
    concept: "تحليل المشهد كاملًا",
    trap: "حسابها حدثًا أقدم لأنها لم تنتهِ.",
  },
  {
    type: "tf",
    ar: "Past Perfect و Past Perfect Continuous يمكن أن يأتيا في نفس الجملة مع Past Simple.",
    answer: true,
    why: "الجملة التي فيها ثلاثة أحداث تجمع العدسات: خلفية + مكتمل قبل + مكتمل مذكور.",
    concept: "تعدد الأزمنة في الجملة",
    trap: "افتراض أن الجملة تحمل زمنًا واحدًا فقط.",
  },
];

// ------------------------------------------------------------
// الدرس 31 — Present Perfect
// ------------------------------------------------------------
const LESSON_31: FinalTestQuestion[] = [
  {
    type: "single",
    ar: "ما صيغة Present Perfect؟",
    options: ["have/has + V3", "had + V3", "have/has been + V-ing", "was + V-ing"],
    answer: 0,
    why: "الصيغة Subject + have/has + V3، و have مع I/You/We/They و has مع He/She/It.",
    concept: "التكوين",
    trap: "استخدام had أو إسقاط has مع he/she/it.",
  },
  {
    type: "single",
    ar: "أكمل:",
    en: "He ____ just finished his homework.",
    options: ["have", "has", "is", "are"],
    answer: 1,
    why: "الفاعل He يأخذ has، و just مع أثر حاضر ⇒ Present Perfect: He has just finished.",
    concept: "have أم has",
    trap: "استخدام have مع He، أو إسقاط الفعل المساعد كليًا.",
  },
  {
    type: "tf",
    ar: "لا نستخدم Present Perfect مع وقت ماضٍ محدد ومنتهٍ مثل yesterday.",
    en: "I have seen him yesterday.",
    answer: true,
    why: "الوقت المحدد المنتهي يطلب Past Simple: I saw him yesterday.",
    concept: "القاعدة الذهبية",
    trap: "الجمع بين has/have و yesterday في جملة واحدة.",
  },
  {
    type: "single",
    ar: "أكمل:",
    en: "I ____ my keys — I can't open the door now.",
    options: ["lose", "lost", "have lost", "had lost"],
    answer: 2,
    why: "النتيجة موجودة الآن (لا أستطيع الدخول) ⇒ Present Perfect.",
    concept: "النتيجة الحالية",
    trap: "اختيار lost لأن فقدان المفاتيح حدث ماضٍ.",
  },
  {
    type: "multi",
    ar: "اختر كل الاستخدامات الصحيحة لـ Present Perfect:",
    options: [
      "تجربة في الحياة (ever / never)",
      "نتيجة موجودة الآن",
      "وقت ماضٍ محدد ومنتهٍ مثل yesterday",
      "فترة زمنية لم تنتهِ بعد (this week)",
      "حالة بدأت في الماضي وما زالت مرتبطة بالحاضر",
    ],
    answers: [0, 1, 3, 4],
    why: "الاستخدامات هي: التجربة · النتيجة · الحدث الحديث · الفترة غير المنتهية · الحالة المستمرة.",
    concept: "خمسة استخدامات",
    trap: "إضافة وقت ماضٍ منتهٍ إلى القائمة.",
  },
  {
    type: "match",
    ar: "صِل الكلمة بمعناها:",
    pairs: [
      { left: "ever", right: "هل سبق أن…؟" },
      { left: "never", right: "لم يسبق أبدًا" },
      { left: "already", right: "بالفعل" },
      { left: "just", right: "للتو" },
      { left: "yet", right: "بعد / حتى الآن" },
      { left: "for", right: "مدة" },
      { left: "since", right: "نقطة بداية" },
    ],
    why: "هذه مفاتيح الكلمات في الدرس، مع حفظ وظيفة كل واحدة.",
    concept: "كلمات Present Perfect",
    trap: "الخلط بين for و since.",
  },
  {
    type: "single",
    ar: "أكمل:",
    en: "I ____ here for five years.",
    options: ["live", "lived", "have lived", "had lived"],
    answer: 2,
    why: "فترة بدأت في الماضي وما زالت مرتبطة بالحاضر ⇒ Present Perfect + for.",
    concept: "الحالة المستمرة",
    trap: "استخدام Past Simple لأن الجملة فيها مدة.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة الصحيحة (be):",
    before: "She",
    after: "to Spain three times.",
    accept: ["has been", "has already been"],
    why: "تجربة في الحياة (ثلاث مرات) ⇒ has + been.",
    concept: "التجربة",
    trap: "استخدام has went.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["He", " has", " went", " to Spain", " three times."],
    answer: 2,
    why: "بعد has نستخدم V3: gone.",
    concept: "V3 بعد have/has",
    trap: "استخدام V2 بعد has.",
  },
  {
    type: "single",
    ar: "أكمل السؤال:",
    en: "How long ____ you known him?",
    options: ["do", "have", "did", "are"],
    answer: 1,
    why: "How long مع الحالة المستمرة ⇒ have + V3.",
    concept: "How long",
    trap: "استخدام do مع how long.",
  },
  {
    type: "order",
    ar: "رتّب الجملة:",
    items: ["Has", "she", "ever", "seen", "snow?"],
    why: "تركيب سؤال التجربة: Has + الفاعل + ever + V3؟",
    concept: "بناء سؤال التجربة",
    trap: "إسقاط تقديم Has على الفاعل، أو وضع ever بعد الفعل.",
  },
  {
    type: "single",
    ar: "ما الفرق؟",
    en: "I saw him yesterday. / I have seen him before.",
    options: [
      "الأولى: وقت محدد منتهٍ · الثانية: تجربة بلا وقت محدد",
      "لا فرق بينهما",
      "العكس تمامًا",
    ],
    answer: 0,
    why: "Past Simple للوقت المحدد، و Present Perfect للتجربة أو الفترة غير المنتهية.",
    concept: "الفرق مع Past Simple",
    trap: "استخدام الزمنين بالتبادل.",
  },
  {
    type: "tf",
    ar: "الإجابة القصيرة الصحيحة: Yes, I have. / No, I haven't.",
    answer: true,
    why: "نعيد نفس الفعل المساعد في الإجابة القصيرة، بلا V3 وبلا تكرار السؤال.",
    concept: "الإجابات القصيرة",
    trap: "إعادة الفعل كاملًا أو استخدام had.",
  },
  {
    type: "single",
    ar: "أي جملة غير صحيحة؟",
    options: [
      "I have visited Spain.",
      "I have seen him yesterday.",
      "She has just arrived.",
      "They have lived here for years.",
    ],
    answer: 1,
    why: "yesterday وقت ماضٍ محدد ومنتهٍ ⇒ يجب استخدام Past Simple.",
    concept: "تطبيق القاعدة الذهبية",
    trap: "قبول الجملة لأنها تبدو سليمة في الترجمة.",
  },
  {
    type: "multi",
    ar: "اختر كل الجمل الصحيحة:",
    options: [
      "I have studied a lot this week.",
      "She has just arrived.",
      "I have lost my keys.",
      "We have met him two years ago.",
    ],
    answers: [0, 1, 2],
    why: "this week فترة لم تنتهِ، just حدث حديث، lost نتيجة حالية؛ أما ago فتطلب Past Simple.",
    concept: "الاستخدامات في سياقها",
    trap: "الخلط مع ago التي تنتمي لـ Past Simple.",
  },
];

// ------------------------------------------------------------
// الدرس 32 — Present Perfect Continuous
// ------------------------------------------------------------
const LESSON_32: FinalTestQuestion[] = [
  {
    type: "single",
    ar: "ما صيغة Present Perfect Continuous؟",
    options: ["have/has been + V-ing", "have/has + V3", "had been + V-ing", "was/were + V-ing"],
    answer: 0,
    why: "شريط النشاط: الفاعل + have/has + been + V-ing، والنشاط يمتد إلى NOW.",
    concept: "التكوين",
    trap: "إسقاط been أو استخدام had في المضارع.",
  },
  {
    type: "single",
    ar: "أكمل:",
    en: "Look! She ____ waiting for an hour.",
    options: ["has been", "have been", "had been", "is been"],
    answer: 0,
    why: "Look! ⇒ ننظر من نقطة الحاضر، و She تأخذ has: has been waiting.",
    concept: "have أم has",
    trap: "استخدام have مع she.",
  },
  {
    type: "tf",
    ar: "هذا الزمن يصف نشاطًا بدأ في الماضي وما زال يترك أثره الآن.",
    answer: true,
    why: "الشريط يمتد من نقطة البداية في الماضي إلى NOW.",
    concept: "معنى الشريط",
    trap: "معاملته كأنه ماضٍ منتهٍ.",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["They", " have", " been", " wait", " since 7:00."],
    answer: 3,
    why: "بعد have been نستخدم V-ing: waiting.",
    concept: "الصيغة بعد been",
    trap: "نسيان ing بعد been.",
  },
  {
    type: "typed",
    ar: "أكمل بالصيغة المستمرة الصحيحة (study):",
    before: "I",
    after: "for two hours.",
    accept: ["have been studying"],
    why: "مدة تمتد حتى الآن ⇒ have been + V-ing.",
    concept: "المدة حتى NOW",
    trap: "استخدام have studied أو was studying.",
  },
  {
    type: "match",
    ar: "صِل العنصر بوظيفته:",
    pairs: [
      { left: "been", right: "جزء ثابت من الصيغة" },
      { left: "V-ing", right: "شكل الفعل بعد been" },
      { left: "for", right: "المدة" },
      { left: "since", right: "نقطة البداية" },
    ],
    why: "أربعة عناصر تُبنى بها كل جملة في الدرس.",
    concept: "لبنات الصيغة",
    trap: "استخدام V3 بعد been.",
  },
  {
    type: "single",
    ar: "أكمل السؤال:",
    en: "How long ____ you been working here?",
    options: ["have", "has", "had", "do"],
    answer: 0,
    why: "you تأخذ have: How long have you been working.",
    concept: "How long",
    trap: "استخدام has مع you.",
  },
  {
    type: "order",
    ar: "رتّب السؤال:",
    items: ["How long", "have", "you", "been", "learning English?"],
    why: "أداة السؤال + have + الفاعل + been + V-ing.",
    concept: "بناء السؤال",
    trap: "وضع been بعد الفاعل أو في آخر السؤال.",
  },
  {
    type: "multi",
    ar: "اختر كل الجمل الصحيحة:",
    options: [
      "I have been reading for two hours.",
      "She has been knowing him for years.",
      "Have you been waiting long?",
      "They haven't been sleeping well.",
    ],
    answers: [0, 2, 3],
    why: "know من أفعال الحالة التي لا تُستخدم عادةً في Continuous.",
    concept: "أفعال الحالة",
    trap: "تطبيق Continuous على كل فعل بلا استثناء.",
  },
  {
    type: "single",
    ar: "أي فعل لا نستخدمه عادةً في الصيغة المستمرة؟",
    options: ["know", "read", "wait", "walk"],
    answer: 0,
    why: "أفعال الحالة (know / like / belong / need…) تبقى في الصيغة البسيطة.",
    concept: "أفعال لا تُستخدم في Continuous",
    trap: "استخدام كل الأفعال في الصيغة المستمرة.",
  },
  {
    type: "tf",
    ar: "أفعال الحالة مثل like و know و belong نستخدمها عادةً في Present Perfect البسيط لا المستمر.",
    answer: true,
    why: "هذه الأفعال تصف حالة لا نشاطًا، والمستمر يصف النشاط.",
    concept: "حالة أم نشاط",
    trap: "«I have been knowing him».",
  },
  {
    type: "single",
    ar: "ما الفرق؟",
    en: "I have painted the wall. / I have been painting the wall.",
    options: [
      "الأولى: نتيجة مكتملة · الثانية: نشاط مستمر وربما لم يكتمل",
      "لا فرق بينهما",
      "الثانية للماضي والأولى للمضارع",
    ],
    answer: 0,
    why: "Present Perfect يركّز على النتيجة، و Present Perfect Continuous على النشاط ومدته.",
    concept: "النتيجة مقابل النشاط",
    trap: "اعتبار الصيغتين مترادفتين.",
  },
  {
    type: "single",
    ar: "في جملة:",
    en: "He has been writing the report.",
    options: [
      "نشاط مستمر وقد لا يكون انتهى",
      "النتيجة مكتملة نهائيًا",
    ],
    answer: 0,
    why: "المستمر يركّز على النشاط نفسه ومدته لا على نتيجة نهائية.",
    concept: "معنى المستمر",
    trap: "قراءة الجملة كأنها «أنجز التقرير».",
  },
  {
    type: "error",
    ar: "اختر المقطع الذي يحتوي الخطأ:",
    segments: ["They", " has", " been", " playing", " all afternoon."],
    answer: 1,
    why: "الفاعل جمع They يأخذ have لا has ⇒ They have been playing.",
    concept: "have أم has مع الفاعل الجمع",
    trap: "استخدام has مع فاعل جمع.",
  },
  {
    type: "single",
    ar: "أي جملة فيها Past Perfect Continuous؟",
    options: [
      "I had been studying before she came.",
      "I have been studying for two hours.",
      "I was studying when she came.",
    ],
    answer: 0,
    why: "had been + V-ing = شريط ممتد قبل نقطة ماضية؛ أما have been فللمضارع.",
    concept: "الفرق بين الماضي والمضارع المستمر",
    trap: "تبديل have بـ had بلا ملاحظة الفرق الزمني.",
  },
];

export const FINAL_TESTS: Record<number, FinalTestQuestion[]> = {
  27: LESSON_27,
  28: LESSON_28,
  29: LESSON_29,
  30: LESSON_30,
  31: LESSON_31,
  32: LESSON_32,
};

/** الدروس التي لها اختبار نهائي مسجّل (تُوسّع مع كل درس جديد) */
export function finalTestLessons(): number[] {
  return Object.keys(FINAL_TESTS)
    .map(Number)
    .sort((a, b) => a - b);
}

/** اختبار درس واحد — يعيد [] إن لم يوجد (والنداء مسؤول عن التعامل مع ذلك) */
export function finalTestFor(lesson: number): FinalTestQuestion[] {
  return FINAL_TESTS[lesson] ?? [];
}
